### ISSUE TITLE
MOSEKLM_LICENSE_FILE seems not to be searched for

### ISSUE THREAD

**Issue by iaravena** [JuliaOpt/Mosek.jl#106]
According to the Readme, the environment variable MOSEKLM_LICENSE_FILE should be checked for a license before going with the default location. In my case, the license is in /opt/Mosek/mosek.lic and the environment variable is set correctly, but Mosek.jl keeps on looking in the default location.
I checked the source and there is no mention to MOSEKLM_LICENSE_FILE. Unfortunately, I am not sure where to include this feature. Is it possible to have this fixed? or to point me to where it would be better to implement this feature, i.e. during build or when loading the module?

**Comment by erling-d-andersen** [comment]
What platform are you working on.

On Linux I know 

   MOSEKLM_LICENSE_FILE

works when done correctly. I.e.

export    MOSEKLM_LICENSE_FILE=...
mosek some_file

should work.

You can set the license search path on runtime if you like.

**Comment by iaravena** [comment]
I am on Linux and it works perfectly outside Julia. The problem occurs when I try to call Mosek from Julia.

**Comment by mlubin** [comment]
Check ``ENV["MOSEKLM_LICENSE_FILE"]`` to see if the variable is actually defined inside Julia.

**Comment by iaravena** [comment]
@mlubin I have just checked. It turns out that MOSEKLM_LICENSE_FILE was defined, but not as part of my environment because I forgot the "export" on my initialization script. Now it works perfectly.
Thanks to both @erling-d-andersen, @mlubin!
