### ISSUE TITLE
options are ignored through LinearQuadratic interface

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Mosek.jl#107]
``MathProgBase.loadproblem!(m::MosekLinearQuadraticModel, ...)`` is missing a call to ``loadoptions!(m)``. The fix is easy, but can we add a test for this somehow?

**Comment by prescient** [comment]
If there is any way this issue could be resolved it would be helpful as I'm currently undertaking a trial evaluation of the product.

**Comment by erling-d-andersen** [comment]
MOSEK here: I will get our Julia expert to look at it tomorrow to see if we
can help getting it fixed.

2017-06-01 2:45 GMT+02:00 prescient <notifications@github.com>:

**Comment by ulfworsoe** [comment]
I have pushed a fix. No test yet.
