### ISSUE TITLE
How to inspect a problem?

### ISSUE THREAD

**Issue by mpf** [JuliaOpt/Mosek.jl#108]
Is there a way to have Mosek print out its view of the problem? I'm thinking in particular of Mosek's [problem analyzer](http://docs.mosek.com/8.0/capi/analyzers.html), but something similar would also be useful.

I tried something like this:

    using Convex, Mosek
    x = Variable(1)
    p = minimize(x, x≥0)
    solve!(p,MosekSolver(MSK_IPAR_LOG_ANA_PRO=1))

But option `MSK_IPAR_LOG_ANA_PRO` doesn't seem to have any effect.

**Comment by ulfworsoe** [comment]
We do not currently have something like that. Unless you are doing SDP you can write a .opf file (supports LP, QP, SOCP and MIP). If you have the `MSKtask` object you can do
```
writedata("mytask.opf")
```
I do not know how to extract the task from a `Convex` model object.

**Comment by mpf** [comment]
Thanks for looking into this!
