### ISSUE TITLE
rcode

### ISSUE THREAD

**Issue by dot-at** [JuliaOpt/Mosek.jl#113]
I think there may be a bug in [line 655 of MosekLPQCQPInterface.jl](https://github.com/JuliaOpt/Mosek.jl/blob/4b586077df0c16680ee03cb3f1196242cdfa8ac1/src/MosekLPQCQPInterface.jl#L655)

**Comment by ulfworsoe** [comment]
You may have to be a bit more specific than that. What happens you see and what do you expect to happen?

**Comment by dot-at** [comment]
When the execution reaches that line, it says err has no field name rcode.
The line number should be 657: `m.lasttrm = err.rcode`

**Comment by ulfworsoe** [comment]
For some reason optimize! produces an unexpected error that is not a `MosekError`. Any non-`MosekError` are now rethrown. You will currently have to check out `master`   
```
Pkg.checkout("Mosek","master")
```
to get the fix. If you get an unexpected error, please open another issue.
