### ISSUE TITLE
Segmentation faults with Julia 0.6.0 and SDPs

### ISSUE THREAD

**Issue by smerkli** [JuliaOpt/Mosek.jl#115]
I found a rather strange problem when using Mosek.jl with Julia 0.6.0 (the release version): 
If I run the below code, Julia will segfault after varying numbers of iterations - usually (but not always) 
in the middle of a Mosek solve.

```
using JuMP
using Mosek

srand(0)
for i = 1:1000
  m = Model(solver=MosekSolver())

  nx = 100
  A = sprand(nx,nx,0.5)
  @variable(m, X[1:nx,1:nx], SDP)
  @constraint(m, trace(A*X) <= 10 )
  @objective(m, :Min, trace(X) )
  solve(m)
end
```

I made some attempts at narrowing down the problem, and here are my notes:
* The same code runs without issues with Julia 0.5.0 and Mosek.jl 0.6.1.
* If the problems are larger, the segfault happens after fewer loop iterations, but the issue 
  occurs with problems as small as `nx = 50`. My system memory is nowhere near fully used,
 and with Julia 0.5, I can easily solve much larger problems without issues.
* If I copy the 0.6.1 version of Mosek.jl into my Julia 0.6.0 release and try that combination,
  I get a bunch of deprecation warnings (which are to be expected, I guess) as well as  this:
   ```ERROR: LoadError: Mosek.MosekError(3944, "The value (0,0) in a sparse symmetric has been specified twice at position 1 and position 3.") Stacktrace:  [1] appendsparsesymmat(::Mosek.MSKtask, ::Int32, ::Array{Int32,1}, ::Array{Int32,1}, ::Array{Float64,1}) at /home/sandro/.julia/v0.6/Mosek/src/msk_functions.jl:389...```.

From these observations, it looks to me like memory is getting corrupted, and the culprit looks to be something with sparse matrix handling - entries getting written multiple times or something of the sort.

I couldn't find out more specifically what is going wrong yet, but I'd be happy to provide more system info or poke around the code further - I thought I'd report this here in case someone can help.

**Comment by ulfworsoe** [comment]
If it crashes in the middle of a solve, it is most likely either internally in MOSEK, or it is in a callback to Julia.

**Comment by smerkli** [comment]
Sometimes it also crashes after Mosek has returned into Julia, when doing seemingly random other stuff - I get the feeling that it tends to segfault when more memory is being allocated later on, but I'm still working on increasing reproducability.

I am using the versions it auto-downloaded, `8.0.0.81` in Julia 0.6 and `8.0.0.57` in Julia 0.5.

**Comment by ulfworsoe** [comment]
Testing with Ubuntu, Julia 0.6.0 and Mosek 8.0.0.81, I have not yet been able to reproduce the crash. 

What kind of system are you running on (OS, processor, memory etc.)? If you can get it to crash under a debugger, can you get a stacktrace?

**Comment by smerkli** [comment]
Interesting - thanks for trying it out! That means I should really test this on more of my own computers to see whether I find a pattern. I also have a real example in which it crashes reliably on my computer, but that's buried deep in some simulation code and I first have to tidy it up into a standalone script.

Let me do some more testing of my own then and I'll report back with my findings.

I'm running on Debian Linux (testing/unstable, x86_64),  8 GB memory and an Intel i7-4600U CPU.
I've used Julia 0.5 and the Mosek interface daily for a few months now and it has been rock solid, but I only
upgraded to Julia 0.6 about a few days ago.

**Comment by smerkli** [comment]
Short update on this: I tested some more and figured out that the combination of Julia 0.6 and linux kernel 4.11 seems to be the only place where the segfaults occur. I tested on 3 separate machines (all running debian, though) and they all had the issue on 4.11, but not on 4.9. I'll try and get my hands on some other distro running kernel 4.11 and see if I can reproduce things there next - that'll hopefully narrow down whether the kernel or something in debian is the problem.

**Comment by smerkli** [comment]
In the meantime, there were more Debian updates (kernel was 4.11.6, now it's 4.11.11) and I ran the problematic cases again - seems the issue is gone now. Since I have not been able to uncover further what causes the issue on 4.11.6 and they are fixed now, I'm closing the issue. We can still reopen it if this problem reappears at a later time. @ulfworsoe : thanks for the help and cross-checking!

For anyone looking at this in the future: I had trouble with **kernel 4.11.6** specifically, now I have **kernel 4.11.11** and things work just fine.
