### ISSUE TITLE
MosekSolver not defined

### ISSUE THREAD

**Issue by krislock** [JuliaOpt/Mosek.jl#117]
I've checked out the master and Pkg.test("Mosek") passes all tests, but I cannot use Mosek with JuMP since I am getting the following error:

julia> using JuMP, Mosek

julia> m = Model(solver = MosekSolver())
ERROR: UndefVarError: MosekSolver not defined

**Comment by ulfworsoe** [comment]
Could I ask you to try v0.8.0 (just releast yesterday, and contains all fixes that are currently in master). I am in the process of factoring `MathProgBase/Mosek` into a separate package so `master` is currently incompatible with `JuMP`.

**Comment by krislock** [comment]
I did Pkg.free("Mosek") then Pkg.update(), giving me v0.7.0 of Mosek.jl, and now MosekSolver works.

Is there a way for me to checkout v0.8.0?

Thanks for your help!

**Comment by ulfworsoe** [comment]
Closing ancient issues.
