### ISSUE TITLE
LoadError: Failed to get MOSEK version

### ISSUE THREAD

**Issue by dot-at** [JuliaOpt/Mosek.jl#124]
On virgin julia installation on Linux, Pkg.add("Mosek") gives this error:
`LoadError: Failed to get MOSEK version`
`while loading...../.julia/v0.6/Mosek/deps/build.jl, in expression starting on line 152`
MOSEKBINDIR is not set.

**Comment by ulfworsoe** [comment]
Hi, I cannot reproduce your problem. Internally the installer uses `wget` or `curl` to download files. Can you verity that you can do
```
curl https://www.mosek.com/downloads/default_dns.txt
```
and
```
curl d2i6rjz61faulo.cloudfront.net/stable/8/version
```

**Comment by ulfworsoe** [comment]
I believe I have fixed the issue in branch "b0.8". I will make a new release soon, until then do:
```
Pkg.checkout("Mosek","b0.8")
```
