### ISSUE TITLE
Mosek package won't build

### ISSUE THREAD

**Issue by imanchester** [JuliaOpt/Mosek.jl#126]
Trying to build the latest Mosek.jl package with JuliaPro 0.6.0.1, I get the following error:

LoadError: Library 'mosekscopt8_1.dylib' not found (/Users/myusername/mosek/8/tools/platform/osx64x86/bin)
while loading /Applications/JuliaPro-0.6.0.1.app/Contents/Resources/pkgs-0.6.0.1/v0.6/Mosek/deps/build.jl, in expression starting on line 226

However, I have checked the folder it is looking in, and the file 'mosekscopt8_1.dylib' is in fact there.

**Comment by ulfworsoe** [comment]
It may mean that it can find the library, but cannot load it due to dependency problems. You can try to do `otool -L mosekscopt8_1.dylib` and check if all dependencies are found.
Most likely it is an installer problem, so I'll take a look at it.

**Comment by imanchester** [comment]
Actually I just noticed what might be the problem. The file I have in my Mosek directory is "libmosekscopt8_1.dylib", but Mosek.jl seems to be looking for "mosekscopt8_1.dylib" (without the "lib")

**Comment by imanchester** [comment]
FYI, here is the output from otool:

otool -L libmosekscopt8_1.dylib
libmosekscopt8_1.dylib:
	libmosekscopt8_1.dylib (compatibility version 0.0.0, current version 8.1.29)
	@loader_path/libmosek64.8.1.dylib (compatibility version 0.0.0, current version 8.1.29)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 855.14.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 59.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	@loader_path/libcilkrts.5.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

**Comment by imanchester** [comment]
Changing line 33 of Mosek/deps/build.jl to include the "lib" seems to have worked.

**Comment by ulfworsoe** [comment]
Thank you. I will make a new release soon.
