### ISSUE TITLE
ExpPrimal problem: incorrect objective value

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Mosek.jl#129]
If I run the following code with Mosek 9 (using `julia --depwarn=no`), I get two different objective values from Mosek on two different transformations of the same ExpPrimal+SOC problem.
```
using ConicBenchmarkUtilities, Convex, MathProgBase

using Mosek
solver = MosekSolver(LOG=0)

# using SCS
# solver = SCSSolver(verbose=0)

x = Variable(1)
y = Variable(1, Positive())
P = minimize(-3x - y,
    x >= 1,
    y >= -2,
    3x + 2y <= 30,
    exp(y^2) + x <= 7)

println("\n\nsolving convex.jl model")
solve!(P, solver)
@show P.optval

println("\n\nwriting, reading, solving cbf model")
name = "expsoc_optimal2"
ConicBenchmarkUtilities.convex_to_cbf(P, name, joinpath(pwd(), "$name.cbf"))
dat = readcbfdata("$name.cbf")
(c, A, b, con_cones, var_cones, vartypes, sense, objoffset) = cbftompb(dat)
m = MathProgBase.ConicModel(solver)
MathProgBase.loadproblem!(m, c, A, b, con_cones, var_cones)
MathProgBase.optimize!(m)
@show MathProgBase.getobjval(m)
```
This is the output:
```
solving convex.jl model
P.optval = -18.082226138528338

writing, reading, solving cbf model
MathProgBase.getobjval(m) = -29.99999999994192
```
Those objective values are very different. Running the same problem with SCS or with Pajarito's cutting plane algorithm yields the first value, -18.082, on both transformations of the problem.

**Comment by chriscoey** [comment]
here is another case. again SCS gives the same objval (8.166) on both but Mosek gives different objvals (8.166 vs 0.0). 

```
using ConicBenchmarkUtilities, Convex, MathProgBase

using Mosek
solver = MosekSolver(LOG=0)

# using SCS
# solver = SCSSolver(verbose=0)

yUB = 3
fe = [1, 0.8, 1, 0.7, 0.7, 0.5, 0.5] .* [1, 2, 1, 1.5, 1.5, 1, 2]
Cout6 = 10
Cout7 = 10
y = Variable(7)
z = Variable(yUB, 7, Positive())
D1 = exp(-y[1]) + exp(-y[1] + y[4])
D2 = 2 * exp(-y[2]) + exp(-y[2] + y[4]) + exp(-y[2] + y[5])
D3 = 2 * exp(-y[3]) + exp(-y[3] + y[5]) + exp(-y[3] + y[7])
D4 = 2 * exp(-y[4]) + exp(-y[4] + y[6]) + exp(-y[4] + y[7])
D5 = exp(-y[5]) + exp(-y[5] + y[7])
D6 = Cout6 * exp(-y[6])
D7 = Cout7 * exp(-y[7])
P = minimize(maximum([
    (D1+D4+D6), (D1+D4+D7), (D2+D4+D6), (D2+D4+D7), (D2+D5+D7), (D3+D5+D6), (D3+D7)
    ]),
    y >= 0,
    sum(fe .* exp(y)) <= 20,
    sum(exp(y)) <= 100)
for i in 1:7
    P.constraints += (sum(z[:,i]) == 1)
    P.constraints += (y[i] == sum([log(j) * z[j,i] for j=1:yUB]))
end

println("\n\nsolving convex.jl model")
solve!(P, solver)
@show P.optval

println("\n\nwriting, reading, solving cbf model")
name = "exp_gatesizing"
ConicBenchmarkUtilities.convex_to_cbf(P, name, joinpath(pwd(), "$name.cbf"))
dat = readcbfdata("$name.cbf")
(c, A, b, con_cones, var_cones, vartypes, sense, objoffset) = cbftompb(dat)
m = MathProgBase.ConicModel(solver)
MathProgBase.loadproblem!(m, c, A, b, con_cones, var_cones)
MathProgBase.optimize!(m)
@show MathProgBase.getobjval(m)
```

**Comment by chriscoey** [comment]
@mlubin mosek seems to get the right answers through the first transformation (no CBF involved) and fails on the CBF

**Comment by chriscoey** [comment]
Given the pattern, I suspect this is not an issue with Mosek itself, but perhaps Mosek.jl, which I had trouble debugging but made a PR for in #128, or potentially mathprogbase or conicbenchmarkutilities (though I don't understand why SCS would give the same answer in both cases but Mosek would differ).

**Comment by chriscoey** [comment]
I believe now the bug is in `MosekConicInterface.jl` around lines 317-328

**Comment by chriscoey** [comment]
The problem seems to happen when there is a constraint ExpPrimal cone that doesn't have simple consecutive indices like `(1,2,3)`. In the MPB conic output from Convex.jl above, we always have `(i,i+1,i+2)`. But in the MPB conic output of CBFs above, we have the reverse: `(i+2, i+1, i)`. In both cases, the MPB conic data is correct, and that is why SCS and Pajarito succeed, and so there is something wrong with how MosekConicInterface deals with the indices on the ExpPrimal cones. Unfortunately I have spent hours trying to understand the code there with little success.

**Comment by ulfworsoe** [comment]
It appears that the primal exponential cone is defined differently by MOSEK and MathProgBase. MOSEK uses 
```
{ (x,y,z) in R^3 | x > y exp(z/y), y > 0,z > 0 }
```
while MPB uses
```
{ (x,y,z) in R^3 | z > y exp(x/y), x > 0,y > 0 }
```
My guess is that the CBF writer uses MOSEK order.
