### ISSUE TITLE
conic indices ignored?

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Mosek.jl#130]
```
using MathProgBase, Mosek

solver = MosekSolver(LOG=0)

c = [0.0, -1.0, -1.0]
A = [1.0  0.0  0.0;
    -1.0  0.0  0.0;
     0.0 -1.0  0.0;
     0.0  0.0 -1.0]
b = [1.0, 0.0, 0.0, 0.0]
con_cones = [(:Zero,1:1), (:SOC,2:4)]
var_cones = [(:Free,[1,2,3])]

# max  y + z
# st   x == 1
#     (x,y,z) in SOC

m = MathProgBase.ConicModel(solver)
MathProgBase.loadproblem!(m, c, A, b, con_cones, var_cones)
MathProgBase.optimize!(m)
@show MathProgBase.getsolution(m)
@show MathProgBase.getobjval(m)

c = [0.0, -1.0, -1.0]
A = [1.0  0.0  0.0;
    -1.0  0.0  0.0;
     0.0 -1.0  0.0;
     0.0  0.0 -1.0]
b = [1.0, 0.0, 0.0, 0.0]
con_cones = [(:Zero,1:1), (:SOC,[4,3,2])]
var_cones = [(:Free,[1,2,3])]

# max  y + z
# st   x == 1
#     (z,y,x) in SOC

m = MathProgBase.ConicModel(solver)
MathProgBase.loadproblem!(m, c, A, b, con_cones, var_cones)
MathProgBase.optimize!(m)
@show MathProgBase.getsolution(m)
@show MathProgBase.getobjval(m)
```
Running that code with latest Mosek using #128 I get the same solution for both problems, even though the SOC indices are reversed, and the second problem should be unbounded.

If I haven't done something silly, this is a major issue, and I am very surprised it has taken this long to be noticed. Fixing this issue of ignoring the indices in the cone (i.e. not just assuming they are consecutive indices like `(2,3,4)`) should also help to fix #129, which I spent all day trying to fix.

@mlubin there need to be tests in MathProgBase/MOI to make sure solvers don't assume consecutive conic indices.

**Comment by ulfworsoe** [comment]
Definitely an error.

In case you can use this feature: You can do `println(m.task)` and get the underlying task formatted nicely (not helpful here - it just shows exactly what you say).

**Comment by ulfworsoe** [comment]
I think it works correctly now. As far as I could see it was only an issue for constraints.

**Comment by mlubin** [comment]
Thanks for the quick fix, @ulfworsoe. Could we get this backported to the latest release on METADATA? This is a serious correctness issue.

(I'm also a bit confused by all the tags at https://github.com/JuliaOpt/Mosek.jl/releases that don't match up with METADATA.)

**Comment by ulfworsoe** [comment]
@mlubin I have used the automated releases since you set it up. I had to set up a scheme with several release branches: b0.6 is for Julia 0.5+Mosek 8.1, b0.7 is Julia 0.6+Mosek 8.1+MPB, b0.8 is Julia 0.6+Mosek 8.1 for MOI. 
Yes, it is a mess.

**Comment by mlubin** [comment]
Ok, I'd recommending backporting to both v0.6.x and v0.7.x.
By the way, does this issue affect the PSD cone?

**Comment by ulfworsoe** [comment]
Yes. I also fixed that.

**Comment by ulfworsoe** [comment]
I already backported the fix, just have to make the releases.
