### ISSUE TITLE
getclist not working

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/Mosek.jl#133]
When calling `getclist` I get
```
ccall: could not find function MSK_getclist in library /home/blegat/mosek/8/tools/platform/linux64x86/bin/libmosek64.so.8.1
```

**Comment by ulfworsoe** [comment]
Which Mosek.jl and Mosek version are you using? 
```
Pkg.version("Mosek"); import Mosek; Mosek.getversion()
```

**Comment by blegat** [comment]
The version of Mosek is `(8, 1, 0, 23)` and I tried both on v0.8.2 and master.

**Comment by ulfworsoe** [comment]
We added a few functions recently. It was added recently in 9.0 (corresponding to master), but is not present in 8.1. If you switch Mosek.jl branch without rebuilding the `Mosek.jl` may try to use a Mosek library that it is not compatible with. `Mosek.jl` b0.8 should be compatible with Mosek 8.1.

**Comment by ulfworsoe** [comment]
Branch `b0.8` (v0.8.*) does not define `getclist`, so most likely you tried using Mosek.jl master with a Mosek 8.1.

**Comment by blegat** [comment]
Ok thanks !
