### ISSUE TITLE
LoadError: Failed to get MOSEK download host in Julia 0.6.2

### ISSUE THREAD

**Issue by erikfilias** [JuliaOpt/Mosek.jl#143]
julia> Pkg.build("Mosek")
INFO: Building Mosek
================================[ ERROR: Mosek ]================================

LoadError: Failed to get MOSEK download host
while loading C:\Users\Erik\.julia\v0.6\Mosek\deps\build.jl, in expression starting on line 150

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Mosek had build errors.

 - packages with build errors remain installed in C:\Users\Erik\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("Mosek")`
 - build a single package by running its `deps/build.jl` script

================================================================================

What can I do for installing Mosek solver in oder to solve Semi Definite Problems?

**Comment by aszekMosek** [comment]
This looks just like no network access at time of installation. Did it work later?

**Comment by erikfilias** [comment]
@aszekMosek Finally, It worked well but I get the next problem:
#144 
Mosek failed the test (Pkg.test("Mosek")), 
Please I need some help,

**Comment by LaurentLessard** [comment]
what did you do to fix your error in the first place? I have the same error message (LoadError: Failed to get MOSEK download host)

**Comment by korpuskel91** [comment]
> @LaurentLessard , I got the free MOSEK license.
> I recommend you to ckeck the Julia version (32 or 64 bits).
> After that, To download the MOSEK from its own web page acording to the Julia (32 bits or 64 bits).
> Install, the MOSEK in your computer, and after that you could install the MOSEK in Julia Language

I did all that and still get the exact same error for Julia 0.6.4. and Mosek 8 for a x86 64bits Windows Machine. Anyone has the same Problem still? Or any tips?

**Comment by aszekMosek** [comment]
Did you set ``MOSEKBINDIR`` as in the install instructions?

**Comment by korpuskel91** [comment]
> Did you set `MOSEKBINDIR` as in the install instructions?

Wow... How could I miss that... Thanks!

**Comment by HuanranLi** [comment]
I think I set everything and I still have this error.

MOSEKDIRBIN: C:\Program Files\Mosek\
MOSEKLM_LICENSE_FILE: C:\Users\Huanran\mosek\mosek.lic

Both julia and Mosek I downloaded is 64 bits version.

Is anything I did wrong for the path?

**Comment by aszekMosek** [comment]
Just to be completely precise, did you set MOSEKDIRBIN or MOSEKBINDIR ? Only the latter is correct.

**Comment by HuanranLi** [comment]
OH..Thank you so much! I'm too dumb to read.
