### ISSUE TITLE
unable to build mosek installation

### ISSUE THREAD

**Issue by sharabhs** [JuliaOpt/Mosek.jl#146]
unable to build my mosek julia installation, i am getting a error message saying 

INFO: Building Mosek
====================================================[ ERROR: Mosek ]====================================================

LoadError: No download agent available; install curl, wget, fetch, or powershell.
while loading C:\Users\shara\.julia\v0.6\Mosek\deps\build.jl, in expression starting on line 152

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: Mosek had build errors.

 - packages with build errors remain installed in C:\Users\shara\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("Mosek")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================

**Comment by erikfilias** [comment]
@sharabhs, do you install the mosek with a license?

**Comment by sharabhs** [comment]
yes I have MOSEK installed on a full academic license.  I can run MOSEK within MATLAB, without any problems.

**Comment by erikfilias** [comment]
@sharabhs , Be careful with the 32/64 bits characteristic. I had a similar problem with the mosek but I identified the problem by checking the line code as you have the next line:
> C:\Users\shara.julia\v0.6\Mosek\deps\build.jl, in expression starting on line 152

**Comment by sharabhs** [comment]
I did check the line, it is some https website, it points to some cloudfront website to pull the distro,

**Comment by sharabhs** [comment]
also, in my atom I get this message "PowerShell version < 3 encountered. Running without wrapper (interrupts won't work).
". I don't know what this is?

**Comment by sharabhs** [comment]
line 152 says this : success(download_cmd(hosturl, joinpath(dldir,"downloadhostname"))) || error("Failed to get MOSEK download host")

**Comment by sharabhs** [comment]
Both my mosek and julia are 64 bit system, including my os

**Comment by sharabhs** [comment]
I am on windows 10.

**Comment by erikfilias** [comment]
@sharabhs , I am working in W10/64 bits with Julia and Mosek in 64 bits, too. 
Try to valid if Julia finds the Mosek's file.

**Comment by sharabhs** [comment]
That is what even I used to work, but unfortunately something happened and I had to reinstall my MOSEK and that is when these things popped up.

**Comment by sharabhs** [comment]
How do i find if my julia can find MOSEK file?

**Comment by sharabhs** [comment]
The environment variables for mosek are defined.

**Comment by erikfilias** [comment]
do you check the MOSEKBINDIR?

**Comment by sharabhs** [comment]
If I do Mosek or mosek in my windows cmd if shows correctly. and Yes it has MOSEK_BIN_DIR = C:\Program Files\Mosek\8\tools\platform\win64x86\bin

**Comment by erikfilias** [comment]
...and have the "Mosek.exe"?

**Comment by sharabhs** [comment]
where?? Mosek.exe

**Comment by sharabhs** [comment]
MOSEK_8_1_EXE = C:\Program Files\Mosek\8\tools\platform\win64x86\bin\mosek.exe

**Comment by erikfilias** [comment]
in the Dir: C:\Program Files\Mosek\8\tools\platform\win64x86\bin
you should have a file called Mosek.exe and mosek64_8_1(.dll and .lib)

**Comment by sharabhs** [comment]
yess its there in my environment variables as in my previous message.

**Comment by sharabhs** [comment]
yess both files are there although, its Mosek.exe and not mosek.exe, does that make any difference?

**Comment by sharabhs** [comment]
sorry its opposite, its mosek.exe and not Mosek.exe as you pointed out.

**Comment by erikfilias** [comment]
Then, Mosek is totally ok.
Julia calls wi the code:

```
function versionFromBindir(bindir ::String)
    try
        mosekbin = if is_windows() "mosek.exe" else "mosek" end
        txt = readstring(`$bindir/$mosekbin`)
        m = match(r"\s*MOSEK Version ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)",txt)
        if m == nothing
            return nothing
        else
            return m.captures[1]
        end
    catch
        return nothing
    end
end

```
Maybe, you can uninstall Julia and everything packages of it. After, install Julia again and try connection with Mosek.

**Comment by sharabhs** [comment]
I already did that several times in hopes of running my mosek but of no avail. Also, I ran the above code you gave and called the function with the string "mosek.exe" it kind of worked with no output.

**Comment by sharabhs** [comment]
Is julia less troublesome on other platforms like mac or linux?

**Comment by erikfilias** [comment]
I think that Julia is less troublesome in linux.

**Comment by sharabhs** [comment]
Okay how do I completely remove julia, like all traces of it besides uninstalling?

**Comment by sharabhs** [comment]
I already did the uninstall removes alldata/folder and also removed the .julia folder including appdata/atom and .atom folder? any registry keys to remove or any other items?

**Comment by erikfilias** [comment]
I think it is preferable that there is no file or register of Julia on your computer.

**Comment by sharabhs** [comment]
But how to do that? Any ideas

**Comment by erikfilias** [comment]
1) uninstall Julia
2) remove temporal files: C:/Windows/Temp ; remove julia file in AppData: %appdata% in C:\Program Files.
3) removing register in cmd: KEY_USERS/.DEFAULT/Software

**Comment by sharabhs** [comment]
Thanks I did everything but I did not find any Julia key in registry that
you pointed.

**Comment by sharabhs** [comment]
Okay so I removed julia and reinstalled mosek still the same problem are you sure this isn't something related to powershell or something??

**Comment by sharabhs** [comment]
So, I fixed MOSEKBINDIR in my julia I was able to install it, installing MOSEK automatically creates MOSEK_8_1_BINDIR, so I thought that is it. But I was wrong, instead the Variable created should be MOSEKBINDIR in julia and re ran the installation, it worked. I am glad, as I depend in MOSEK. 

I am closing this as my problem stands fixed and anyone same problem use this fix, Thanks!!
