### ISSUE TITLE
`mskvmajor` and `mskvminor` values are wrong making build fail

### ISSUE THREAD

**Issue by jd-lara** [JuliaOpt/Mosek.jl#150]
The current values of `mskvmajor` and `minor` are set up as 9 and 0 respectively in `build.jl` 

https://github.com/JuliaOpt/Mosek.jl/blob/eb2a26710658b20b940442a976703a82d1d3157f/deps/build.jl#L4

https://github.com/JuliaOpt/Mosek.jl/blob/eb2a26710658b20b940442a976703a82d1d3157f/deps/build.jl#L5

The latest version of Mosek as per the [webpage](https://www.mosek.com/downloads/) is 8.1. This mismatch makes the build fail

**Comment by ulfworsoe** [comment]
I think you have accidentially checked out the `master` branch. The revision you link to is (at the moment of writing) the head revision in the `master` branch. you should probably use version `v0.9.1` or if you want all fixes for the 0.9 branch, use branch `b0.9` .

**Comment by jd-lara** [comment]
@ulfworsoe is Mosek 9.0 coming out soon? Yes, I checked out master

**Comment by erling-d-andersen** [comment]
We have plan to have a beta available early next year. If you want to
testdrive then send an email to support@mosek.com.

Den ons. 3. okt. 2018 kl. 22.46 skrev Jose Daniel Lara <
notifications@github.com>:
