### ISSUE TITLE
MosekMathProgModel numvar field is broken

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/Mosek.jl#16]
The field is not updated when variables are added internally (for instance, when auxiliary variables are created in `addquadconstr!`); this bit me for pretty much the whole weekend when I couldn't find out why multiple quadratic constraints were breaking :(

It seems that there is no reason to carry around this state when it's liable to break like this and a call to `getnumvar(m.task)` is so easy. I'm not sure if there was a reason to do it this way that I'm missing @ulfworsoe @wflu, but if not I'll go through the MathProgBase interface and change it.

**Comment by madeleineudell** [comment]
I think I'm seeing an error related to this: on the `warmstart` branch of Convex, trying
```
using Convex, Mosek

set_default_solver(MosekSolver())

x = Variable()
y = Variable()

p = minimize(x+y, x>=0, y>=0)
solve!(p)

y.value = 4
fix!(y)
solve!(p)
```
gives the error
```
MOSEK error 1241: Too small maximum number of variables 0 is specified. Currently, the number of variables is 3.
ERROR: MosekError(1241,"Too small maximum number of variables 0 is specified. Currently, the number of variables is 3.")
 in putmaxnumvar at /Users/madeleine/.julia/v0.3/Mosek/src/msk_functions.jl:2992
 in loadconicproblem! at /Users/madeleine/.julia/v0.3/Mosek/src/MosekConicInterface.jl:235
 in load_problem! at /Users/madeleine/.julia/v0.3/Convex/src/solution.jl:81
 in solve! at /Users/madeleine/.julia/v0.3/Convex/src/solution.jl:27
```
(If this problem is unrelated I'll open a separate issue.)

**Comment by ulfworsoe** [comment]
I think this is a separate issue. It appears that MOSEK has changed behaviour so putmaxnumvar cannot remove variables.

**Comment by ulfworsoe** [comment]
I have replace the putmax... with resizetask. Could you check if it fixes the problem?

**Comment by madeleineudell** [comment]
Great! That fixes it.

**Comment by ulfworsoe** [comment]
Closing
