### ISSUE TITLE
Install error: Mosek + Julia 0.6.4 = ERRORS

### ISSUE THREAD

**Issue by elbrandt** [JuliaOpt/Mosek.jl#163]
Hello,
I am trying to install Mosek using Julia 0.6.4. I am required to use 0.6.4 and cannot update.

I have Mosek binaries installed (8.1.0.67) on my Win7 machine. I have MOSEKBINDIR set properly

Any help you can provide would be very much appreciated.
As the documentation said, after initial failures,  I tried Pkg.checkout("Mosek","master"), and my trials/responses that I get now are shown below.

I don't know much about Julia packages, but inside the ...JuliaPro-0.6.4.1\pkgs-0.6.4.1\v0.6\Mosek folder, the file 'REQUIRE' contains a line 'julia 0.7'... so maybe I have the wrong version of Mosek.jl somehow? If so, how do I fix/downgrade it to be compatible with 0.6.4?

Thank you in advance for your help,
-Eric.

In Julio 0.64 I did the following:

Pkg.add("Mosek")

> INFO: Package Mosek is already installed
> INFO: METADATA is out-of-date — you may not have the latest version of Mosek
> INFO: Use `Pkg.update()` to get the latest versions of your packages
> 

Pkg.build("Mosek")
> INFO: Building Mosek
> ================================[ ERROR: Mosek ]================================
> 
> LoadError: LoadError: ArgumentError: Module Pkg not found in current path.
> Run `Pkg.add("Pkg")` to install the Pkg package.
> while loading C:\Users\ebrandt\AppData\Local\JuliaPro-0.6.4.1\pkgs-0.6.4.1\v0.6\Mosek\deps\liftedfrombindeps.jl, in expression starting on line 5
> while loading C:\Users\ebrandt\AppData\Local\JuliaPro-0.6.4.1\pkgs-0.6.4.1\v0.6\Mosek\deps\build.jl, in expression starting on line 1
> 
> ================================================================================
> 
> ================================[ BUILD ERRORS ]================================
> 
> WARNING: Mosek had build errors.
> 
>  - packages with build errors remain installed in C:\Users\ebrandt\AppData\Local\JuliaPro-0.6.4.1\pkgs-0.6.4.1\v0.6
>  - build the package(s) and all dependencies with `Pkg.build("Mosek")`
>  - build a single package by running its `deps/build.jl` script
> 
> ================================================================================

using Mosek

> INFO: Precompiling module Mosek.
> ERROR: LoadError: ArgumentError: Module SparseArrays not found in current path.
> Run `Pkg.add("SparseArrays")` to install the SparseArrays package.
> Stacktrace:
>  [1] _require(::Symbol) at .\loading.jl:435
>  [2] require(::Symbol) at .\loading.jl:405
>  [3] include_from_node1(::String) at .\loading.jl:576
>  [4] include(::String) at .\sysimg.jl:14
>  [5] anonymous at .\<missing>:2
> while loading C:\Users\ebrandt\AppData\Local\JuliaPro-0.6.4.1\pkgs-0.6.4.1\v0.6\Mosek\src\Mosek.jl, in expression starting on line 3
> Failed to precompile Mosek to C:\Users\ebrandt\AppData\Local\JuliaPro-0.6.4.1\pkgs-0.6.4.1\lib\v0.6\Mosek.ji.
> 
> Stacktrace:
>  [1] compilecache(::String) at .\loading.jl:710
>  [2] _require(::Symbol) at .\loading.jl:497
>  [3] require(::Symbol) at .\loading.jl:405
>

**Comment by elbrandt** [comment]
I cannot explain why the incorrect version was installed, but I fixed it with:
Pkg.rm("Mosek")
Pkg.add("Mosek")

**Comment by richardrl** [comment]
I got a similar error: "in expression starting at /Users/richard/.julia/packages/Mosek/5QnPP/deps/build.jl:151"

Fixed it by:
1. Exiting Julia
2. Running the Pkg.rm, Pkg.add @elbrandt said

seems like julia maintains some cached state that needs to be reset if you didn't install / set permissions for the separate mosek application correctly at first
