### ISSUE TITLE
SDP doesnt solve using MOSEK, throws error "no method matching : setindex_shape_check(::Int64, ::Int64)"

### ISSUE THREAD

**Issue by taranjitsinghb** [JuliaOpt/Mosek.jl#164]
This is a sample example of an SDP optimization problem. The JuMP parses amazingly to solve it with SCS and CSDP solvers. However, I noticed that these solvers fail to solve larger systems (restarts Julia), which eventually I will using to solve linear control problems. And hence, I would require Mosek to solve these problems. My ultimate idea is to use Pajarito for MISDP problems.

Here is the code:
```julia
using JuMP, LinearAlgebra, Mosek, SCS, CSDP
A = [  -0.8715    0.5202    0.7474    1.0778   -0.9686    0.1005;
       -0.5577   -1.0843    1.8912    0.2523    1.0641   -0.0345;
       -0.2615   -1.7539   -1.5452   -0.2143    0.0923   -2.4192;
        0.6087   -1.0741    0.1306   -2.5575    2.3213    0.2388;
       -0.7169    0.3582   -1.4195    1.7043   -2.6530   -1.4276;
       -1.2944   -0.6752    1.6983    1.6764   -0.3646   -1.7730 ];
 B = [       0    0.8998   -0.2130    0.9835;
             0   -0.3001         0   -0.2977;
       -1.0322         0   -1.0431    1.1437;
             0   -0.3451   -0.2701   -0.5316;
       -0.4189    1.0128   -0.4381         0;
             0         0   -0.4087         0];
 C = [      0    2.0034         0    1.0289    0.1554    0.7135;
       0.9707    0.9510    0.7059    1.4580   -1.2371    0.3174;
            0         0    1.4158    0.0475   -2.1935    0.4136;
      -0.4383    0.6489   -1.6045    1.7463   -0.3334   -0.5771];
md = Model(solver = MosekSolver(LOG=0))
#md = Model(solver = SCSSolver())
#md = Model(solver = CSDPSolver())
@variable(md,P[1:6,1:6],SDP)
@variable(md, γ)
@objective(md,Min, γ)
I3 = Matrix{Float64}(I,4,4);
T = [A'*P + P*A + C'*C P*B; B'*P -γ*I3];
@SDconstraint(md, T<=0)
print(md)
solve(md)
γ = sqrt(getvalue(γ))
```

Thank You.

**Comment by blegat** [comment]
What is the issue with Mosek ? If I understood correctly, you mention that it doesn't work with SCS and CSDP but don't say anything about Mosek failing.

**Comment by blegat** [comment]
Could you try `] add Mosek#bl/fix164` and let us know if it resolve your issues ?

**Comment by taranjitsinghb** [comment]
Hello, I tried this. But I still see the same error. Thank you.

**Comment by blegat** [comment]
Are you sure ? Have you restarted Julia ? I tested it with your code and I get the error before the change and it is fixed after the change

**Comment by taranjitsinghb** [comment]
Aha, I think I was doing something wrong after the fix, It works. All thanks to you.

**Comment by blegat** [comment]
Closed by https://github.com/JuliaOpt/Mosek.jl/pull/165
