### ISSUE TITLE
Packaging of Mosek + MOI

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/Mosek.jl#168]
Currently, to use Mosek with JuMP master, the user needs to do
```julia
using MathOptinterfaceMosek
model = Model(with_optimizer(MosekOptimizer))
```
while for any other solver, it is
```julia
using Solver
model = Model(with_optimizer(Solver.Optimizer))
```
This lack of consistency makes Mosek less convenient to use for JuMP users.
I understand that having a separate package for the Mosek API and for the Mosek implementation of MOI is appropriate (as discussed in https://github.com/JuliaOpt/MathOptInterfaceMosek.jl/pull/34#issuecomment-385674555).
However, we could have them separate while still allowing `Mosek.Optimizer` to be an MOI optimizer.
I see two options for that:
1. have three packages: MosekInterface.jl (Mosek API access), MathOptInterfaceMosek.jl (Mosek with MOI) and Mosek.jl (basically just loads the two other ones)
2. have two packages: MosekInterface.jl (Mosek API access), Mosek.jl (Mosek with MOI)

@ulfworsoe What do you think ?

**Comment by ulfworsoe** [comment]
I would be very sorry to change `Mosek.jl` as the low-level API name since this is consistent with all namespace/module naming in all other MOSEK interfaces, and it would break existing code using the low-level interface.

`MathOptInterfaceMosek.jl` was chosen only because the early versions of other interfaces did something similar, so I am not married to that. As alternative names I would suggest
- `JLMosek`, corresponding to the naming of our RMosek package
- `MosekTools` which is the official name for the package (e.g. of you download the mosek package)

**Comment by odow** [comment]
In `Mosek.jl` define
```julia
function Optimizer(args...; kwargs...)
    error("To use Mosek with JuMP (or MathOptInterface), you need to import ",
          "the package `MosekTools` (via `import MosekTools`). You may need ",
          "to first install it via `import Pkg; Pkg.add("MosekTools")`.")
end
```

Then `MosekTools` can overload `Mosek.Optimizer` and everything will work. Users still get to use `Mosek.Optimizer`, the api's are split, and no weird `MathOptInterfaceMosek`.

**Comment by blegat** [comment]
@ulfworsoe `MosekTools` looks better indeed. It is the name if you download the package from where ?
@odow I like the idea (although, strictly speaking, this is type-piracy).

**Comment by ulfworsoe** [comment]
@blegat The name of the binary Mosek package is `mosektools[platform]` and the MOSEK solver and associated functionality are called "MOSEK Tools" (as apposed to Toolbox, which is the MATLAB API).
@odow That looks like a creative solution we will never regret. I approve!

**Comment by blegat** [comment]
You won't get a warning if the signature is more specific, e.g. `Mosek.Optimizer(; kws...)` which is more specific as it does not have any positional arg

**Comment by blegat** [comment]
The approach seems to work. So the plan is

1. Merge https://github.com/JuliaOpt/Mosek.jl/pull/171
2. Tag Mosek v0.9.9
3. Merge https://github.com/JuliaOpt/MathOptInterfaceMosek.jl/pull/69
4. Rename MathOptInterfaceMosek to MosekTools
5. Tag MosekTools v0.6.0

Sounds good ?

**Comment by odow** [comment]
Are you sure? Have you tested to see if there is a conflict? What happens with `Mosek.Optimizer()`? That seems ambiguous to me...

**Comment by blegat** [comment]
Yes, you can test it with `Mosek#master` and `MathOptInterfaceMosek#master`, it works without warning. See also this minimal example
```julia
julia> f() = 1
f (generic function with 1 method)

julia> f(args...) = 2
f (generic function with 2 methods)

julia> f()
1

julia> f(:a)
2
```

**Comment by blegat** [comment]
MosekTools has just been released
