### ISSUE TITLE
Mosek 9.0

### ISSUE THREAD

**Issue by chiumichael** [JuliaOpt/Mosek.jl#177]
I have installed Mosek 9.0. But Mosek.jl seems to be 8.0. I checked some of the older issues that, to my understanding, say that removing and readding the package should force Mosek.jl to download the latest version, but it does not seem to be doing so. Is there a way I can manually point Mosek.jl to the 9.0 I have installed. I do not have 8.0 installed manually.

Any help would be greatly appreciated!

**Comment by blegat** [comment]
IIUC (@ulfworsoe correct me if I am wrong), the current release of Mosek.jl which is on the b0.9 branch (https://github.com/JuliaOpt/Mosek.jl/tree/b0.9) is for Mosek v8.0:
https://github.com/JuliaOpt/Mosek.jl/blob/5996662b755779f0c5bf20b4e61eb94af7728f95/deps/build.jl#L4-L5
The development for Mosek v9.0 is done on the master branch:
https://github.com/JuliaOpt/Mosek.jl/blob/efebef81c8c81812a686668618bce386c25f8bd8/deps/build.jl#L4-L5
but there has been no release yet. You can try it with `import Pkg; Pkg.add(Pkg.PackageSpec(name="Mosek", rev="master"))` or just `] add Mosek#master` in the REPL.

**Comment by ulfworsoe** [comment]
I have made a release for MOSEK 9.0. It should be available when it has been approved, meaning that installing or upgrading the MOSEK package should give you a MOSEK 9.0. Note that licenses for 8.1 will probably not work with 9.0.

MOSEK has been out in a beta version, but we only just released officially recently, and we are in the process of making 9.0 the default version.

**Comment by CynthiaChenyx** [comment]
may I ask how you install Mosek9.0?
When I input Pkg.add(Pkg.PackageSpec(;name="Mosek", version="9.0")) I received the message that I was inputting wrong version in Julia 1.0.5

**Comment by chiumichael** [comment]
I haven’t used this in a while, but after downloading their tarbells, I unzipped it to some directory and added that directory to my path.

Hope this helps.
