### ISSUE TITLE
Julia 1.1.0 ERROR: LoadError: Failed to unpack MOSEK distro

### ISSUE THREAD

**Issue by OVGULIU** [JuliaOpt/Mosek.jl#178]
```
 Pkg.build("Mosek")
  Building Mosek → `C:\Users\david\.julia\packages\Mosek\vBHcL\deps\build.log`
┌ Error: Error building `Mosek`:
│ [ Info: get version
│ [ Info: mosekbin = mosek.exe
│ [ Info: get version
│ [ Info: mosekbin = mosek.exe
│ [ Info: Get latest MOSEK version (https://d2i6rjz61faulo.cloudfront.net/stable/8/version)
│ [ Info: Latest MOSEK version = 8.1.0.80
│ [ Info: No MOSEK version currently installed
│ [ Info: Download MOSEK distro (https://d2i6rjz61faulo.cloudfront.net/stable/8.1.0.80/mosektoolswin64x86.zip)
│ [ Info: Unpack MOSEK distro (C:\Users\david\.julia\packages\Mosek\vBHcL\deps\downloads/mosektoolswin64x86.zip -> C:\Users\david\.julia\packages\Mosek\vBHcL\deps\src)
│ ERROR: LoadError: Failed to unpack MOSEK distro
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\david\.julia\packages\Mosek\vBHcL\deps\build.jl:208
│  [3] include at .\boot.jl:326 [inlined]
│  [4] include_relative(::Module, ::String) at .\loading.jl:1038
│  [5] include(::Module, ::String) at .\sysimg.jl:29
│  [6] include(::String) at .\client.jl:403
│  [7] top-level scope at none:0
│ in expression starting at C:\Users\david\.julia\packages\Mosek\vBHcL\deps\build.jl:110
```

**Comment by ulfworsoe** [comment]
It looks like the unpack command fails to run, but I cannot see what is wrong.

Can you try to replace line 201 in deps/build.jl with:
```
run(unpack_cmd(joinpath(dldir,archname),srcdir, ext, sndext))
```
and rerun?

**Comment by OVGULIU** [comment]
thank you!

I have replaced the line 201, then 

│ ERROR: LoadError: failed process: Process(`unzip 'C:\Users\david\.julia\packages\Mosek\TE1Nu\deps\downloads\mosektoolswin64x86.zip' -o '-dC:\Users\david\.julia\packages\Mosek\TE1Nu\deps\src'`, ProcessExited(11)) [11]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at .\process.jl:726
│  [4] run(::Cmd) at .\process.jl:724
│  [5] top-level scope at C:\Users\david\.julia\packages\Mosek\TE1Nu\deps\build.jl:202
│  [6] include at .\boot.jl:326 [inlined]
│  [7] include_relative(::Module, ::String) at .\loading.jl:1038
│  [8] include(::Module, ::String) at .\sysimg.jl:29
│  [9] include(::String) at .\client.jl:403
│  [10] top-level scope at none:0
│ in expression starting at C:\Users\david\.julia\packages\Mosek\TE1Nu\deps\build.jl:105

**Comment by ulfworsoe** [comment]
Thank you. Ok, for some reason unzip fails. You can bypass `unzip` if you do insert at `deps/liftedfrombindeps.jl` line 97:
```
has_zip = false
```
If this works for you I'll update the code and make a new release.

**Comment by OVGULIU** [comment]
@ulfworsoe , nice! it works now!

with kind regard!
