### ISSUE TITLE
Julia 1.1.1 ERROR: To use Mosek 9.0 with JuMP 0.19.2

### ISSUE THREAD

**Issue by erikfilias** [JuliaOpt/Mosek.jl#180]
I just installed Mosek 9.0 and added the Mosek.jl package to Julia 0.19.2, sucessfully. 
However, I had the following error when I ran it:
![image](https://user-images.githubusercontent.com/8010477/61463728-e0190480-a929-11e9-8b87-fafe684b5330.png)

And, when I tried to add MosekTools.jl, I had the following error:
![image](https://user-images.githubusercontent.com/8010477/61474817-4e67c200-a93e-11e9-846a-3dfa381376c4.png)

Please, let me know. What can I do in order to use the Mosek.jl?

**Comment by blegat** [comment]
Should be resolved once https://github.com/JuliaRegistries/General/pull/2125 is merged

**Comment by erikfilias** [comment]
> Should be resolved once [JuliaRegistries/General#2125](https://github.com/JuliaRegistries/General/pull/2125) is merged

I just updated it.
Thanks a lot!!
