### ISSUE TITLE
Add bridge for SOS1 and SOS2 constraints

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaOpt/Mosek.jl#182]
Since Mosek does not support SOS1 and SOS2 constraints it would be nice to have a bridge to automatically reformulate these into simpler constraints.
[Linke in the Mosek cookbook](https://docs.mosek.com/modeling-cookbook/mio.html#continuous-piecewise-linear-functions)

**Comment by odow** [comment]
Closing in favor of https://github.com/JuliaOpt/MathOptInterface.jl/issues/845 since this is best handled by an MOI bridge.
