### ISSUE TITLE
MosekSolver not defined

### ISSUE THREAD

**Issue by jkim22** [JuliaOpt/Mosek.jl#183]
Hi, I am using Convex.jl along with Mosek.jl to solve an optimization problem.

When I try to run the following:

using Convex;
using Mosek;

problem = Convex.minimize(cost, constraints);
solve!(problem, MosekSolver());

it keep says "MosekSolver not defined". However, when I do Pkg.test("Mosek") it successfully passes all issues.

Can someone please help me on this... I've installed Mosek 9.0. I've already seen previous issue on this and it seems it does not resolve mine.

I even tried: Pkg.add(Pkg.PackageSpec(name="Mosek", rev="master"))

and still I cannot resolve this issue... Thanks.

**Comment by blegat** [comment]
The support for MathProgBase was removed:
https://github.com/JuliaOpt/Mosek.jl/blob/f727e24a146ebf35f766db252b27ba09fb375ed2/src/Mosek.jl#L288-L295
Use either an older version of Mosek.jl or using the MathOptInterface:
https://github.com/JuliaOpt/MosekTools.jl
that can be used with JuMP v0.19 and later.
@ericphanson is working on the transition of Convex.jl to MathOptInterface

**Comment by jkim22** [comment]
Ok Thanks. Does that mean Convex.jl cannot use the newer version of Mosek.jl along with Mosek 9.0? I wonder this because my problem involes with exponential cone problem which older version of Mosek cannot solve...

Also, can you help me how to use older version of Mosek.jl? 

I tried Pkg.add("Mosek", v"0.8.0")  but it seems not working. 

Thanks alot!

**Comment by ericphanson** [comment]
> Does that mean Convex.jl cannot use the newer version of Mosek.jl along with Mosek 9.0?

Yes, looking at the code it seems like the versions of Mosek.jl compatible with Mosek 9.0 removed MathProgBase support which Convex relies on to send the problems to the solver. 

If you're willing to try something a bit more work-in-progress, you can try using Convex with MathOptInterface (which is compatible with Mosek 9.0) already (or you can wait until we release it as part of Convex.jl proper). First, you need to add my branch of Convex, and MosekTools
```julia
]add https://github.com/ericphanson/Convex.jl#MathOptInterface
]add MosekTools
```
and then use it just as before, with `Mosek.Optimizer()` replacing `MosekSolver()`:
```julia
using Convex, MosekTools
...
solve!(problem, Mosek.Optimizer())
```
With SCS, this branch passes almost all of Convex's tests; just a few things fail which weren't implemented yet. I also didn't implement getting dual variables for constraints yet. That being said, there definitely could be bugs; if use this branch and find any bugs, please report them on the usual Convex.jl repo (https://github.com/JuliaOpt/Convex.jl) and mention you're using my MOI branch. That would be very helpful!

**Comment by jkim22** [comment]
Thanks for the comment. However, I tried following:

Pkg.add(PackageSpec(url="https://github.com/ericphanson/Convex.jl") )
Pkg.add("MosekTools) ) 

and try 

using Convex, MosekTools
...
solve!(problem, Mosek.Optimizer())

but it still gives me error

MethodError: no method matching solve!(::Problem, ::MosekModel)
Closest candidates are:
  solve!(::Problem; warmstart, check_vexity, verbose) at /Users/jongho/.julia/packages/Convex/cow0j/src/solution.jl:21
  solve!(::Problem, !Matched::MathProgBase.SolverInterface.AbstractMathProgSolver; kwargs...) at /Users/jongho/.julia/packages/Convex/cow0j/src/solution.jl:12

I guess the problem is Convex.jl with MathOptInterface not working well. 

When I try 

Pkg.add(PackageSpec(url="https://github.com/ericphanson/Convex.jl#MathOptInterface") )

it gives error:

failed to clone from https://github.com/ericphanson/Convex.jl#MathOptInterface

Is the branch of Convex correct..? Thanks.

**Comment by jkim22** [comment]
I see, I tried using Convex with MathOptInterface and MosekTools and it works.

Thanks.

**Comment by jkim22** [comment]
Oh One more thing...

I got the following error:

Cannot `convert` an object of type MathOptInterface.ZeroOne to an object of type MathOptInterface.AbstractVectorSet

I guess it is issue with MathOptInterface... right?

**Comment by jkim22** [comment]
It looks like Convex with MathOptInterface and MosekTools cannot work with mixed integer (e.g. Boolean) problem?

I tried following toy example and it gives the same error:

# Data taken from http://people.sc.fsu.edu/~jburkardt/datasets/knapsack_01/knapsack_01.html
w = [23; 31; 29; 44; 53; 38; 63; 85; 89; 82]
C = 165 
p =  [92; 57; 49; 68; 60; 43; 67; 84; 87; 72];
n = length(w)

using Convex, MosekTools
x = Variable(n, :Bin)
problem = maximize(dot(p, x), dot(w, x) <= C)
solve!(problem, Mosek.Optimizer())

MethodError: Cannot `convert` an object of type MathOptInterface.ZeroOne to an object of type MathOptInterface.AbstractVectorSet

**Comment by ericphanson** [comment]
Ah, thanks for the report! That's my fault; I just pushed a fix, so if you do `] up Convex` it should pull it down. Note that it seems MosekTools needs MathOptInterface version 0.8 while the latest is version 0.9 it seems; to get it to run, I had to do
```julia
]rm MosekTools
]add MathOptInterface@0.8 MosekTools
```
otherwise it gave errors about ambiguous methods. It turns out also I wasn't testing as much as I thought I was, and it turns out one of the tests for `matrixfrac` is failing on my branch; I'll try to get that fixed soon.

**Comment by blegat** [comment]
> otherwise it gave errors about ambiguous methods

MosekTools v0.9 should work with MOI v0.9, could you file a bug report to MosekTools with the error you get ?

**Comment by ericphanson** [comment]
Looking at it again, I think it's not an error with MosekTools but rather with my MOI branch:
```julia
ERROR: MethodError: MathOptInterface.supports_constraint(::Convex.MOIModel{Float64}, ::Type{MathOptInterface.SingleVariable}, ::Type{MathOptInterface.ZeroOne}) is ambiguous. Candidates:
  supports_constraint(model::Convex.MOIModel{#156#T}, ::Type{#s110} where #s110<:Union{SingleVariable, ScalarAffineFunction{#156#T}}, ::Type{#s108} where #s108<:Union{Integer, ZeroOne}) where #156#T in Convex at /Users/eh540/.julia/packages/MathOptInterface/mvlGI/src/Utilities/model.jl:997
  supports_constraint(::MathOptInterface.Utilities.AbstractModel{T}, ::Type{MathOptInterface.SingleVariable}, ::Type{#s176} where #s176<:Union{Integer, ZeroOne, EqualTo{T}, GreaterThan{T}, Interval{T}, LessThan{T}}) where T in MathOptInterface.Utilities at /Users/eh540/.julia/packages/MathOptInterface/mvlGI/src/Utilities/model.jl:469
Possible fix, define
  supports_constraint(::Convex.MOIModel{T}, ::Type{MathOptInterface.SingleVariable}, ::Type{#s176} where #s176<:Union{Integer, ZeroOne})
```
Sorry for blaming MosekTools!

**Comment by blegat** [comment]
@ericphanson No problem ;) You can fix it with the hint given by the first bullet here: https://github.com/JuliaOpt/MathOptInterface.jl/issues/736

**Comment by jkim22** [comment]
Hi, 

I am using following package versions 

 "Convex"           => v"0.12.2"
  "Mosek"            => v"1.0.4"
  "MathOptInterface" => v"0.8.4"

and tried this problem:

# Data taken from http://people.sc.fsu.edu/~jburkardt/datasets/knapsack_01/knapsack_01.html
w = [23; 31; 29; 44; 53; 38; 63; 85; 89; 82]
C = 165 
p =  [92; 57; 49; 68; 60; 43; 67; 84; 87; 72];
n = length(w)

using Convex, MosekTools
x = Variable(n, :Bin)
problem = maximize(dot(p, x), dot(w, x) <= C)
solve!(problem, Mosek.Optimizer())

Although it seems work, I realized that all values of x's are NaN.

problem.optval = 309.0

x 

Variable of
size: (10, 1)
sign: NoSign()
vexity: AffineVexity()
value: [NaN; NaN; NaN; NaN; NaN; NaN; NaN; NaN; NaN; NaN]

Since there is no error in MosekTools, I guess it is issue with Convex.jl ??

**Comment by ericphanson** [comment]
Yup, another bug, thanks again! That is now fixed, as is the incompatability with MathOptInterface 0.9. I also added MathOptInterface v0.9 to the compat entry, which means you shouldn't have to specify a version yourself (and if you have pinned it to 0.8 like I suggested earlier, you'll need to remove it with `]rm MathOptInterface` first, and then update to the latest version of my branch with `]up Convex`).

I also rewrote much of the interface with MOI so it should be more performant (we no longer generate the old MathProgBase standard form first and then send it to MOI, instead sending it a bit more directly).

**Comment by jkim22** [comment]
Thanks, I think it now works (meaning Convex.jl along with MosekTools v0.9)

Is it possible to set time limit for Mosek.Optimizer() ??

when I try 

```Julia
Mosek.Optimizer(TimeLimit=1000) 
```
it gives me
MOSEK error 1207: The parameter name 'MSK_IPAR_TimeLimit' is invalid for an int parameter.
