### ISSUE TITLE
How to set 'dualize' parameter of Mosek?

### ISSUE THREAD

**Issue by TongCHEN779** [JuliaOpt/Mosek.jl#185]
I use Yalmip with Mosek solver for Matlab. When I write an SDP problem, I can do something like

options = sdpsettings('solver', 'mosek', 'dualize', 1);

so that Mosek solver know whether I want to solve the dual or the primal.

However, for Julia, how can I do the same parameter setting?

using SumOfSquares
using MosekTools
model = SOSModel(with_optimizer(Mosek.Optimizer))

Thanks in advance.

**Comment by blegat** [comment]
It will use the primal, i.e. variables in cones and linear constraints. If you want to use the dual, use https://github.com/JuliaOpt/Dualization.jl/ (check the documentation there and let us know if the doc is not clear enough)

**Comment by ulfworsoe** [comment]
Not a MOSEK solver API issue.
