### ISSUE TITLE
Mosek v9.1

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/Mosek.jl#191]
@ulfworsoe What's the plan for Mosek v9.1 support ? I see that there is both a branch b1.0-msk9.1 and a branch msk9.1.

**Comment by blegat** [comment]
Apparently it is b1.1-msk9.1 that was used to tag Mosek.jl v1.1

**Comment by ulfworsoe** [comment]
Yes. Sorry it took so long. After a long discussion about how exactly compatibility between minor Mosek version work, I decided that it was safer bump the minor version of Mosek.jl for each minor versions of Mosek.

**Comment by blegat** [comment]
No problem, I just opened the issue as a reminder that README should be updated once the final name of the branch is chosen.
