### ISSUE TITLE
unable to install mosek in julia 

### ISSUE THREAD

**Issue by duyanran** [JuliaOpt/Mosek.jl#198]
```
(@v1.3) pkg> add MosekTools
  Resolving package versions...
  Installed WinReg ───── v0.3.1
  Installed Mosek ────── v1.1.3
  Installed MosekTools ─ v0.9.3
   Updating `C:\Users\duyanran\.juliapro\JuliaPro_v1.3.1-2\environments\v1.3\Project.toml`
  [1ec41992] + MosekTools v0.9.3
   Updating `C:\Users\duyanran\.juliapro\JuliaPro_v1.3.1-2\environments\v1.3\Manifest.toml`
  [6405355b] + Mosek v1.1.3
  [1ec41992] + MosekTools v0.9.3
  [1b915085] + WinReg v0.3.1
   Building Mosek → `C:\Users\duyanran\.juliapro\JuliaPro_v1.3.1-2\packages\Mosek\6LuE3\deps\build.log`
┌ Error: Error building `Mosek`: 
│ [ Info: Download command: `powershell -file 'C:\Users\duyanran\.juliapro\JuliaPro_v1.3.1-2\packages\Mosek\6LuE3\deps\winget.ps1' https://www.mosek.com/downloads/default_dns.txt 'C:\Users\duyanran\.juliapro\JuliaPro_v1.3.1-2\packages\Mosek\6LuE3\deps\downloads\downloadhostname'`        
│ ┌ Error: �޷������ļ� C:\Users\duyanran\.juliapro\JuliaPro_v1.3.1-2\packages\Mos
│ │ ek\6LuE3\deps\winget.ps1����Ϊ�ڴ�ϵͳ�Ͻ�ֹ���нű����й���ϸ��Ϣ����
│ │ ���� https:/go.microsoft.com/fwlink/?LinkID=135170 �е� about_Execution
│ │ _Policies��
│ │     + CategoryInfo          : SecurityError: (:) []��ParentContainsErro
│ │     rRecordException
│ │     + FullyQualifiedErrorId : UnauthorizedAccess
│ └ @ Main C:\Users\duyanran\.juliapro\JuliaPro_v1.3.1-2\packages\Mosek\6LuE3\deps\build.jl:203
│ ERROR: LoadError: Failed to get MOSEK download host
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\duyanran\.juliapro\JuliaPro_v1.3.1-2\packages\Mosek\6LuE3\deps\build.jl:204
│  [3] include at .\boot.jl:328 [inlined]
│  [4] include_relative(::Module, ::String) at .\loading.jl:1105        
│  [5] include(::Module, ::String) at .\Base.jl:31
│  [6] include(::String) at .\client.jl:424
│  [7] top-level scope at none:5
│ in expression starting at C:\Users\duyanran\.juliapro\JuliaPro_v1.3.1-2\
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.3.1\share\julia\st`
<img width="406" alt="1592055555(1)" src="https://user-images.githubusercontent.com/56710672/84570193-5e8e5880-adbe-11ea-9aa7-06df68bd72df.png">
```
is there anyone can help me solve this problem ?
thanks a lot !!!

**Comment by hans-riess** [comment]
I am having similar issues. Thanks in advance!

> ``julia> Pkg.build("Mosek")
 Building Mosek → `~/.julia/packages/Mosek/6LuE3/deps/build.log`
┌ Error: Error building `Mosek`: 
│ [ Info: Download command: `curl -o /home/hans/.julia/packages/Mosek/6LuE3/deps/downloads/downloadhostname -L https://www.mosek.com/downloads/default_dns.txt`
│ [ Info: Get latest MOSEK version (https://d2i6rjz61faulo.cloudfront.net/stable/9.2/version)
│ [ Info: Latest MOSEK version = 9.2.14, nothing currently installed
│ [ Info: Download MOSEK distro (https://d2i6rjz61faulo.cloudfront.net/stable/9.2.14/mosektoolslinux32x86.tar.bz2)
│ [ Info: Unpack MOSEK distro (/home/hans/.julia/packages/Mosek/6LuE3/deps/downloads/mosektoolslinux32x86.tar.bz2 -> /home/hans/.julia/packages/Mosek/6LuE3/deps/src)
│ ERROR: LoadError: Failed to unpack MOSEK distro
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /home/hans/.julia/packages/Mosek/6LuE3/deps/build.jl:256
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1044
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:392
│  [7] top-level scope at none:0
│ in expression starting at /home/hans/.julia/packages/Mosek/6LuE3/deps/build.jl:144
└ @ Pkg.Operations /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1096``

**Comment by aszekMosek** [comment]
@hans-riess This file ``mosektoolslinux32x86.tar.bz2`` does not exist, there is no 32bit Linux Mosek distro. What is your operating system?

**Comment by ulfworsoe** [comment]
I think these are two different issues.

@duyanran I think this is a problem we have seen before. The build script uses a PowerShell script to download the Mosek distribution, and on some windows installations a Powershell security policy blocking execution of the script. 
I have not been able to reproduce this issue, but there are two solution I have seen work for others:
- Either change the script execution policy for Powershell, or
- Install the Mosek distro manually in your home directory (`C:\Users\duyanran\mosek`).

**Comment by ulfworsoe** [comment]
@hans-riess We do not support 32bit linux anymore. I think the is that the Mosek.jl package does not have correct platform requrements set up.
