### ISSUE TITLE
Issue with Pkg.build("Mosek")

### ISSUE THREAD

**Issue by dehann** [JuliaOpt/Mosek.jl#21]
Hi,

I'm having a build issue with Pkg.add("Mosek"). Please see printout below

Mosek bin/ directory is in my PATH as well as the MOSEKBINDIR environment variable. I can launch Mosek from a terminal just fine. It seems to be failing at line 81 in the build.jl file:

@BinDeps.install [ :libmosek => :libmosek ]

Any ideas? Please see below.

Ubuntu 12.04 (64)
gcc 4.6

Thanks

Pkg.build("Mosek")
INFO: Building Mosek
==========================================[ ERROR: Mosek ]===========================================

None of the selected providers can install dependency libmosek.
Use BinDeps.debug(package_name) to see available providers

while loading /home/dehann/.julia/Mosek/deps/build.jl, in expression starting on line 81

=====================================================================================================

==========================================[ BUILD ERRORS ]===========================================

WARNING: Mosek had build errors.

 - packages with build errors remain installed in /home/dehann/.julia
 - build a package and all its dependencies with `Pkg.build(pkg)`
 - build a single package by running its `deps/build.jl` script

=====================================================================================================

**Comment by ulfworsoe** [comment]
See issue #41 .
