### ISSUE TITLE
Mosek.jl fails JuMP nonlinear test

### ISSUE THREAD

**Issue by ulfworsoe** [JuliaOpt/Mosek.jl#24]
Mosek reports "nonconvex problem" during first test in
```
JuMP/test/nonlinear.jl
```
Trace:
```
ERROR: Mosek.MosekError(1291,"The optimization problem is nonconvex.")
 in optimize at /home/ulfw/.julia/Mosek/src/msk_functions.jl:2498
 in optimize! at /home/ulfw/.julia/Mosek/src/MosekSolverInterface.jl:660
 in solvenlp at /home/ulfw/.julia/JuMP/src/nlp.jl:485
 in solve at /home/ulfw/.julia/JuMP/src/solvers.jl:6
 in anonymous at /home/ulfw/.julia/JuMP/test/nonlinear.jl:32
 in context at /home/ulfw/.julia/FactCheck/src/FactCheck.jl:282
 in anonymous at /home/ulfw/.julia/JuMP/test/nonlinear.jl:14
 in facts at /home/ulfw/.julia/FactCheck/src/FactCheck.jl:261
 in include at ./boot.jl:242
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:242
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:300
 in _start at ./client.jl:382
 in _start_3B_3993 at /usr/local/julia/bin/../lib/julia/sys.so
while loading /home/ulfw/.julia/JuMP/test/nonlinear.jl, in expression starting on line 12
while loading /home/ulfw/.julia/JuMP/test/runtests.jl, in expression starting on line 28
```

**Comment by mlubin** [comment]
@ulfworsoe, this test still seems to be failing. Any idea why the strange return status?

**Comment by ulfworsoe** [comment]
That looks a bit funny... From the log it looks like the status should be at least NEAR_OPTIMAL. Do you have the return value from Mosek.optimize()?

**Comment by mlubin** [comment]
I added some debugging statements to Mosek.jl:
```
optimize(m.task) => 0
soldef => 2
prosta => 0
solsta => 0
```

**Comment by ulfworsoe** [comment]
I cannot rule out that it is a bug in the solver that sets a wrong status. I will try to debug it.

**Comment by mlubin** [comment]
It could also be a bug in the NLP wrapper I wrote.

**Comment by ulfworsoe** [comment]
A very quick test: If I insert
```
  solutionsummary(task_,MSK_STREAM_LOG)
  println(getsolsta(task_,MSK_SOL_ITR))
```
in the `Mosek.optimize()` function, immediately after the native function has been called, I can see that the interior-point solution is optimal, and that solution status for `MSK_SOL_ITR` is 1 (optimal). Is it possible that you accidentally modify the task so the status changes after `optimize()`?

**Comment by ulfworsoe** [comment]
It looks like you ask for the integer solution, `MSK_SOL_ITG`, rather than the interior, `MSK_SOL_ITR`.

**Comment by mlubin** [comment]
Right, ``getsoldef`` is returning ``MSK_SOL_ITG``:
```
solutiondef(m.task,MSK_SOL_ITG) => true
solutiondef(m.task,MSK_SOL_BAS) => true
solutiondef(m.task,MSK_SOL_ITR) => true
```

**Comment by ulfworsoe** [comment]
Yes, I can see that. I am not sure where those solutions come from... Do you at any point input an initial solution or somthing like that?

**Comment by mlubin** [comment]
Yes, JuMP always gives a starting point:
https://github.com/JuliaOpt/Mosek.jl/blob/master/src/MosekSolverInterface.jl#L719
It looks like this logic needs to be tweaked?

**Comment by ulfworsoe** [comment]
You could check if solution is defined and not unknown, perhaps? Problem is that MOSEK will not delete an inputted solution.
