### ISSUE TITLE
Exposing geometric programming interface

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/Mosek.jl#28]
It seems the geometric programming interface is not included in the shared library in the Mosek distro, but rather through some C routines that wrap around the existing API and are accessible to the user through the `dgopt`/`expopt` executables. Since we need a shared library to call from Julia, ideally it would be great to bundle the routines into the shared library. If that is not possible (at least in the short term), what is the viability of someone porting the C code to Julia? It doesn't seem extremely complex (and I'd be potentially willing to do the work at some point), but I'm unclear how the licensing would work out. Thoughts?

cc @ulfworsoe @mlubin

**Comment by ulfworsoe** [comment]
Closing ancient issues.
