### ISSUE TITLE
Mosek fails Convex.jl SDP tests

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Mosek.jl#29]
On the master branch of ``Convex.jl``, we can test Mosek as a solver by modifying ``test/run_tests.jl``
with
```
using Mosek
set_default_solver(MosekSolver())
```
to run the tests using Mosek. Mosek is currently failing the SDP tests with the error
```
ERROR: MosekError(3942,"An element in the upper triangular part at row 0 in column 1 has been specified.")
```
CC @karanveerm @madeleineudell

**Comment by ulfworsoe** [comment]
Converning this: https://groups.google.com/forum/#!topic/julia-opt/S7WFuNs32Y8

I am trying to run the Convex.jl tests with Mosek and find that test_sdp.jl fails. The issue seems to be that MOSEK expects a n*(n+1)/2 indexes for an n*n semidefinite variable (or constraint), and Convex.jl gives it n*n indexes. Does anyone know that status on this? Should the MathProgBase conic interface accept a full matrix or an upper/lower triangular part?

@joehuchette

**Comment by mlubin** [comment]
Convex.jl hasnt switched yet to the lower triangular input format, but the Mosek interface is doing the right thing here.

**Comment by madeleineudell** [comment]
We have a [branch of Convex.jl](https://github.com/madeleineudell/convex.jl/tree/lower_tri_sdp) that uses the new lower triangular input format. Mosek seems to solve a problem (correctly?), but the interface can't return the solution (`ERROR: MosekMathProgModelError("No solution available")`). Test code below:
```
using Convex
using Mosek

n = 3
A = reshape(1:n^2, n, n)
A[:,1] = 0
I = ifelse(A .== -1.0, 0.0, 1.0);
R = Variable(size(A))
problem = minimize( nuclear_norm(R), [vecnorm((R-A).*I) <= 2000] )

# c, A, b, cones look right to me
c, A, b, cones, var_to_ranges, vartypes, conic_constraints = conic_problem(problem)

# fails to return solution
solve!(problem, MosekSolver())
```

**Comment by madeleineudell** [comment]
cc @jduchi

**Comment by ulfworsoe** [comment]
The problem MOSEK gets is dual infeasible. I can't say yet whether this is because of an error in the API, but I am looking into it.

**Comment by ulfworsoe** [comment]
It is a bit complicated to reverse engineer the problem received by loadconicproblem!(), but the SDP part of the A matrix looks suspicious, and the PSD constraint is 8x8, where I would expect 3x3.

**Comment by madeleineudell** [comment]
Here's a feasible test problem with the same size as the one I posted
previously:
```
using Convex
using Mosek

n = 3
A = rand(n, n)
R = Variable(size(A))
problem = minimize( nuclear_norm(R), vecnorm(R-A) <= 3 )

# c, A, b, cones look right to me
c, A, b, cones, var_to_ranges, vartypes, conic_constraints =
conic_problem(problem)

# fails to return solution
solve!(problem, MosekSolver())
```
The dimension of the SDP should be 6 x 6, using the identity
`nuclear_norm(A)` is equal to the optimal value of
```
minimize (trace(U) + trace(V))/2
subject to
         [U A; A' V] is positive semidefinite
```
So the lower triangular part should be 6 (6 + 1) / 2, or 21:
```
julia> cones
5-element Array{(Symbol,UnitRange{Int64}),1}:
 (:SDP,1:21)
 (:Zero,22:36)
 (:Zero,37:37)
 (:SOC,38:47)
 (:NonNeg,48:48)
```


On Thu, Jun 4, 2015 at 4:09 AM, Ulf Worsøe <notifications@github.com> wrote:

> It is a bit complicated to reverse engineer the problem received by
> loadconicproblem!(), but the SDP part of the A matrix looks suspicious, and
> the PSD constraint is 8x8, where I would expect 3x3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Mosek.jl/issues/29#issuecomment-108843832>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by ulfworsoe** [comment]
Ok. This one just gives solution status "unknown". I'll investigate, but it may just mean that the solver failed or stalled.

**Comment by ulfworsoe** [comment]
The elements in the lower triangular part of the SDP cone are specified row-wise in the data I get, but loadconicproblem!() expects them to be ordered column-wise. 
I don't think the data order is mentioned in the docs, so I am not sure if this is correct.

**Comment by mlubin** [comment]
From the docs: 

> For the semidefinite cone, the number of variables or constraints present correspond to the lower (or upper) triangular elements in column-major (resp., row-major) order.

So it could be row-wise if you view it as the upper triangle.

**Comment by ulfworsoe** [comment]
Sorry. Maybe I should RTFM. In any case it looks like `loadconicproblem!()` gets the tril of A in row-major order.

**Comment by mlubin** [comment]
@madeleineudell, would it be hard to switch to column-major order?

**Comment by madeleineudell** [comment]
ok, i've made the switch to column major. there are still 4 tests that don't pass: but interestingly, Mosek and SCS return *different* incorrect values. i've examined the conic form problem (`c, A, b, cones`) for the following problem in detail and it looks right to me.
```
using Convex

y = Semidefinite(2)
p = minimize(nuclear_norm(y), y[2,1]<=4, y[2,2]>=3, y[1,1]<=2)
c, A, b, cones, _ = conic_problem(p)

solve!(p)
p.optval == evaluate(nuclear_norm(y)) # should be true
```
The answer should be 3. SCS gives a value of 2.12 and Mosek gives a value of 1.5. @bodono @ulfworsoe 

Interestingly, both seem to give the right answer for the entries of `y`...

For convenience, here's code to reconstruct all n^2 entries of the matrix that should be PSD corresponding to the 5:14th (n(n-1)/2) rows of A:
```
A = reshape(p.solution.primal[1:4], (2,2))
U = reshape(p.solution.primal[5:8], (2,2))
V = reshape(p.solution.primal[9:12], (2,2))
eigvals([U A'; A V]) # should all be >= 0
```

**Comment by ulfworsoe** [comment]
I can reproduce the result. It looks like some row/column bug in the formulation. The problem I recieve looks like this (more or less):
```
min x12
s.t. x12 = 1/2(x4+x7+x8+x11)
     |x0    |
     |x2  x3| is PSD

     |x4           |
     |x5 x7        |
     |x0 x1 x8     |  is PSD
     |x2 x3 x9 x11 |
     
     x0 < 2, x1 < 4, x3 > 3
```
The PSD variable y is defined by `[x0,x2,x2,x3]`, but `[x0,x2,x1,x3]` are used in the 4x4 PSD constraint, and constraints are placed on `x0`, `x1` and `x3`. I think in this case `x1` should be replaced by `x2` everywhere. More generally, only elements from the lower triangular part of an PSD variable should be referenced.

**Comment by madeleineudell** [comment]
My current approach to formulation is to specify that the lower triangular
part of a matrix is PSD, and to place equality constraints relating the
lower and upper trial glad parts ensuring symmetry. I do this instead of
explicitly eliminating the variables corresponding to the upper triangular
part. This makes it easier to reconstruct the solution I to a form that
will make sense to the user (who is allowed to place constraints ts on both
lower and upper triangular parts of the matrix).

In the formulation for that problem in particular, there should also be a
few equality constraints: eg,  x1==x2; which should make the problem
equivalent to the formulation you propose.

**Comment by ulfworsoe** [comment]
Ok, that should work too.

And I found the (or at least a) bug: There was no 1/2 on offdiagonal slacks in PSD constraints. It now gives the solution 3.0 for the problem you sent. I cannot guarantee that there are not other errors in the API.

**Comment by bodono** [comment]
FYI: Looks like there might be a bug in SCS for SDPs, see https://github.com/cvxgrp/scs/issues/40. I'm investigating right now, but it might be best not to rely on SCS for verification until I've figured out what's happening.

**Comment by madeleineudell** [comment]
@ulfworsoe thanks! I pulled from Mosek master and rebuilt the package to see if that will be sufficient, but now I'm getting `MosekMathProgModelError("No solution available")` errors again. Any ideas?

(For comparison, SCS returns solutions, but occasionally ones that are wrong, probably due to the issue @bodono mentioned.)

**Comment by bodono** [comment]
You probably have the SCS solutions scaled by sqrt(2), the same as happening in cvxpy (e.g. 3/sqrt(2) = 2.12 which you were getting before). I'm figuring out the best way to fix it at the moment, but it might require passing the data scaled by sqrt(2), as in the presentation from Mosek pg 6-7: http://docs.mosek.com/slides/ismp2012/sdo.pdf

**Comment by ulfworsoe** [comment]
@madeleineudell You get errors on the same problem you sent earlier? That is strange - I just pulled Mosek and your Convex branch and it solves to optimality.
If it is other problems you get errors on: If you send the problem, I can take a look at it. It may simply be that MOSEK fails to find an optimal solution.

**Comment by bodono** [comment]
@madeleineudell here is some information about the SCS SDP input format that might be useful: https://github.com/cvxgrp/scs/issues/40

**Comment by madeleineudell** [comment]
@ulfworsoe I was referring to the Convex.jl [test suite for SDPs](https://github.com/JuliaOpt/Convex.jl/blob/master/test/test_sdp.jl). Happily, it turns out the only test still failing is the one that originated this thread, whose solution is not attained. 

So I'm ready to say that Convex.jl *can* solve SDPs with Mosek at this point!

**Comment by ulfworsoe** [comment]
@madeleineudell It looks like when I run with Julia 0.3 the `Convex.jl` tests pass, but when running with Julia 0.4 (from yesterday) one test fails. I'll see if I can figure out what the problem is.

**Comment by ulfworsoe** [comment]
Correction: I get "No solution" both for 0.3 and 0.4.

**Comment by madeleineudell** [comment]
That should just be the problem with unbounded solution. I've decided
that's not an entirely fair test, so I've commented it out in my most
recent PR.

There seems to be [one more test not passing](
https://github.com/JuliaOpt/Convex.jl/blob/master/test/test_affine.jl#L278).
It's a trivial problem. Any idea why it's not returning a solution?

On Tue, Jun 9, 2015 at 11:33 AM, Ulf Worsøe <notifications@github.com>
wrote:

> Correction: I get "No solution" both for 0.3 and 0.4.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Mosek.jl/issues/29#issuecomment-110457187>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by ulfworsoe** [comment]
Mosek reports it primal infeasible. If you look at the A, b and cones you get from `conic_problem()` you can see that the last constraint in the problem is `0 = -1`.

**Comment by ulfworsoe** [comment]
Btw. I don't think the unbounded solution cases are unfair as such. You should just not let status=UNKNOWN count as an error - only incorrect solution should really count.

**Comment by mlubin** [comment]
@ulfworsoe, what doesn't the interface return ``:Infeasible`` status in this case?

**Comment by ulfworsoe** [comment]
The comment about status=UNKNOWN was related to this problem
```
min y_11
s.t. y_21 = 1, y is PSD(2,2)
```
It has an infinite optimal solution and MOSEK 7.1 stalls. I think the result status=UNKNOWN should not be considered an error, only an actual incorrect solution should be an error.

**Comment by madeleineudell** [comment]
I've found another problem on which Mosek throws an error rather than returning infeasible. Any ideas why?
```
    x = Variable(3)
    p = minimize(sum(x), x >= 1, diagm(x)[1, 2] == 1)
    solve!(p, MosekSolver())
```

**Comment by ulfworsoe** [comment]
It looks like constraint 5 is empty and = 1 (basically 0 = 1), making it infeasible.

**Comment by ulfworsoe** [comment]
If you get MOSEK to write a .task file of the problem, you can use this to view it:
https://github.com/MOSEK/TaskViewer

**Comment by mlubin** [comment]
It looks like the original issue is resolved. If anything is still broken, we should open a new issue.
