### ISSUE TITLE
Transition from MOSEK 7.0 to 7.1 (and later to 8.0)

### ISSUE THREAD

**Issue by ulfworsoe** [JuliaOpt/Mosek.jl#32]
We recently released MOSEK 7.1, deprecating 7.0.

I have discovered some problems in the installer (`deps/build.jl`): 
- all version numbers are hardcoded, and
- builder does not check if the downloaded file (the mosek distro) has been updated - this is a problem since the url for Mosek 7.1 is exactly the same as for 7.0 (7.1 has replaced 7.0, and 7.0 cannot be downloaded anymore), but the library names are not the same. 

So: 
- Should we say that the newest Mosek.jl only supports  the latest Mosek? 
- Is there a way to automatically force redownload, even if the url has not changed (but the actual file has)?

cc @mlubin @IainNZ

**Comment by mlubin** [comment]
> Should we say that the newest Mosek.jl only supports the latest Mosek?

Yes, that's certainly reasonable for now.

> Is there a way to automatically force redownload, even if the url has not changed (but the actual file has)?

Not really, I've been complaining about this for quite a long time: JuliaLang/BinDeps.jl#26. What you can do is add a validator for the library that checks if the version is correct (e.g, https://github.com/JuliaOpt/GLPK.jl/blob/master/deps/build.jl#L11) and then print a useful error message instructing users to remove old directory in the case where an old library is found.

**Comment by ulfworsoe** [comment]
I have gone over the install script and simplified it a lot: Instead of unpacking and copying the libraries, I managed to just let the library path point to the right place. This means that I can add aliases for both 7.0 and 7.1 libraries, without knowing which actual libraries are present, which in turn means that it will work, even if you do not update the mosek binaries to 7.1. When we get to Mosek 8.0 we will switch the installer to 8.0 and require binaries to be updated.

I think the best way to fix the distro re-download problem is to write a relacement for BinDeps' download-and-unpack functionality (basically: let the downloader save a timestamp, when rebuilding, fetch the timestamp and compare to the old, re-download if not up to date). Should be simple enough.

**Comment by mlubin** [comment]
Sounds good! You shouldn't feel tied to using BinDeps. It has a number of significant limitations, and we've moved away from it entirely in the Gurobi wrapper.

**Comment by tkelman** [comment]
You could try something like the tag-file approach that Steven Johnson is using in his small Blosc package: https://github.com/stevengj/Blosc.jl/blob/master/deps/build.jl

**Comment by ccoffrin** [comment]
Bumping this becouse Mosek 8 is out now.  :-)

**Comment by ulfworsoe** [comment]
I will see if I can get the tagging scheme to work.

I will probably also stop supporting other MOSEK versions that the newest in main branch.

**Comment by ulfworsoe** [comment]
The build script now writes a file under `deps/` with the version of the currently installed MOSEK distro. Running `Pkg.build("Mosek")` again will check this against the latest version online and re-download if necessary.
If you use an external MOSEK that was not initially installed by the build script, new versions will not be downloaded.
