### ISSUE TITLE
return status for timeout

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Mosek.jl#43]
Another issue once #42 is resolved. When Mosek hits the time limit, it currently returns ``:Unknown`` status through the MPB interface. This should be ``:UserLimit``. How can we detect if the solver stopped because of a time limit?

**Comment by ulfworsoe** [comment]
Yes. Optimize returns an MSK_RES_... code. MSK_RES_OK means that the optimizer stopped in a normal way, MSK_RES_TRM_... gives you the reason for termination. There are several codes that can be mapped to :UserLimit (MAX_ITERATIONS, NUM_SETBACKS, MAX_TIME etc., all depending on values that the user can set).

**Comment by mlubin** [comment]
Is this return value available afterwards (through ``soldef``, ``prosta``, or ``solsta``?) or do we need to store it ourselves?

**Comment by ulfworsoe** [comment]
You will have to store it. It is not stored in the task object.

**Comment by ulfworsoe** [comment]
This should work now.
