### ISSUE TITLE
Mosek is broken in latest Julia 0.4

### ISSUE THREAD

**Issue by ulfworsoe** [JuliaOpt/Mosek.jl#47]
I have been notified that Mosek.jl is broken in the latest Julia 0.4 (probably due to this: https://groups.google.com/forum/#!topic/julia-dev/uQ1DsGGSrD0).
I would like to make a branch of Mosek for Julia 0.3 so I can start fixing the problem and remove deprecations for Julia 0.4.
What is the best way to do this?

**Comment by mlubin** [comment]
The standard practice is to use the ``Compat`` package which lets you write
code that's compatible with 0.3 and 0.4 simultaneously without deprecation
warnings. I can take a look at the issues here later today.

**Comment by mlubin** [comment]
The package has been working on 0.4 for a while now
