### ISSUE TITLE
Indexing error when mixing SDP and SOCP

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/Mosek.jl#49]
The following JuMP code produces an internal indexing error:
```jl
using JuMP

m = Model()

@defVar(m, x[1:1,1:1], SDP)
@defVar(m, y)
@defVar(m, z >= 0)
@defVar(m, t >= 0)
@addConstraint(m, (y-1)^2 <= z^2)
@addConstraint(m, (x[1,1]-1)^2 <= t^2)

solve(m)
```
```
ERROR: Mosek.MosekError(1204,"The index value 7 occurring in argument '(asub+aptrb[1])[0]' is too large.")
 in putarowslice at /Users/huchette/.julia/v0.4/Mosek/src/msk_functions.jl:2644
 in putarowslice at /Users/huchette/.julia/v0.4/Mosek/src/msk_functions.jl:2622
 in addquadconstr! at /Users/huchette/.julia/v0.4/Mosek/src/MosekLowLevelQCQO.jl:148
 in addQuadratics at /Users/huchette/.julia/v0.4/JuMP/src/solvers.jl:87
 in solveSDP at /Users/huchette/.julia/v0.4/JuMP/src/solvers.jl:622
 in solve at /Users/huchette/.julia/v0.4/JuMP/src/solvers.jl:27
```

**Comment by joehuchette** [comment]
MPB calls:
```jl
using MathProgBase, Mosek
model = MathProgBase.model(MosekSolver())
MathProgBase.loadconicproblem!(model, 
    [0.0,0.0,0.0,0.0],
    sparse(Int[], Int[],Float64[], 0, 4),
    Float64[],Any[],Any[(:SDP,1:1),(:NonNeg,[3,4]),(:Free,[2])])
MathProgBase.addquadconstr!(model, 
    Int32[2,2],
    [-1.0,-1.0],
    Int32[2,3],
    Int32[2,3],
    [1.0,-1.0],
    '<',
    -1.0)
MathProgBase.addquadconstr!(model, 
    Int32[1,1],
    [-1.0,-1.0],
    Int32[1,4],
    Int32[1,4],
    [1.0,-1.0],
    '<',
    -1.0)
```
The error is in this second call to ``addquadconstr!``.

**Comment by joehuchette** [comment]
This works to reproduce something similar:
```jl
using MathProgBase, Mosek
model = MathProgBase.model(MosekSolver())
MathProgBase.loadconicproblem!(model, 
    [0.0,0.0,0.0,0.0],
    sparse(Int[], Int[],Float64[], 0, 4),
    Float64[],Any[],Any[(:SDP,1:1),(:NonNeg,[3,4]),(:Free,[2])])
MathProgBase.addquadconstr!(model, 
    Int32[2,2],
    [-1.0,-1.0],
    Int32[2,3],
    Int32[2,3],
    [1.0,-1.0],
    '<',
    -1.0)
MathProgBase.addquadconstr!(model, 
    Int32[1,1],
    [-1.0,-1.0],
    Int32[1,4],
    Int32[1,4],
    [1.0,-1.0],
    '<',
    -1.0)
```
```
ERROR: Mosek.MosekError(1204,"The index value 5 occurring in argument '(asub+aptrb[1])[0]' is too large.")
 in putarowslice at /Users/huchette/.julia/v0.4/Mosek/src/msk_functions.jl:2644
 in putarowslice at /Users/huchette/.julia/v0.4/Mosek/src/msk_functions.jl:2622
 in addquadconstr! at /Users/huchette/.julia/v0.4/Mosek/src/MosekLowLevelQCQO.jl:148
```

**Comment by mlubin** [comment]
I don't think it was ever intended that you could mix ``loadconicproblem!`` and ``addquadconstr!``.

**Comment by ulfworsoe** [comment]
I think we are out somewhere in the "in theory it should work but I'd appreciate if you didn't test it" territory. I'll take a look at it.

**Comment by mlubin** [comment]
In theory it should work, but conic solvers which support SDP and SOCP
definitely don't need to implement the quadratic interface as well. I.e.,
this wont work for SCS.

**Comment by joehuchette** [comment]
If we don't want to mix that's fine, though there should be an error saying so I guess. I just didn't want to get into the game of doing the transformation (new variables) from quadratic to SOC in JuMP.

**Comment by mlubin** [comment]
There's no new variables needed to convert to conic form, just some rows of
the constraint matrix which belong to SOC.

**Comment by joehuchette** [comment]
Moses adds new variables internally, but yes you are right if you have the expression as ``Σ aff^2 <= t^2``.
If you have everything in terms form, not sure how best to convert it to this form. Should probably just hold off for the ``norm`` stuff.

**Comment by mlubin** [comment]
Wait,
```
@addConstraint(m, (y-1)^2 <= z^2)
@addConstraint(m, (x[1,1]-1)^2 <= t^2)
```
aren't even in standard SOCP-via-quadratic form. What do you expect to happen? When you pass this to Mosek, it goes into quadratic mode, not conic mode, afaik.

**Comment by joehuchette** [comment]
This is culled from an example from about a year ago that used to work fine (with the old JuMP/Mosek interface). Not sure if it was going through the conic mode or not.

**Comment by mlubin** [comment]
I think the SDP code in JuMP should throw an error when there's a quadratic constraint that's not in standard SOCP form. Manually doing the extra variables is annoying, but we'll hopefully have a better solution soon.

**Comment by mlubin** [comment]
@joehuchette, okay to close this?
