### ISSUE TITLE
Unboundedness not detected on unconstrained SDP

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/Mosek.jl#50]
The following JuMP code produces an optimal solution instead of unboundedness:
```jl
using JuMP

m = Model()
@defVar(m, X[1:1,1:1], SDP)
@setObjective(m, Max, X[1,1])
stat = solve(m) # => :Optimal

getValue(X) # =>
# 1x1 Array{Float64,2}:
#  0.0
```
If I add a linear constraint, this behavior goes away.

**Comment by joehuchette** [comment]
MBP calls:
```jl
using MathProgBase, Mosek
model = MathProgBase.model(MosekSolver())
MathProgBase.loadconicproblem!(model, 
    [1.0],
    sparse(Int[], Int[],Float64[], 0, 1),
    Float64[],
    Any[],
    Any[(:SDP,1:1)])
MathProgBase.setsense!(model, :Max)
MathProgBase.optimize!(model)
```

**Comment by joehuchette** [comment]
Bump. @ulfworsoe any ideas?

**Comment by ulfworsoe** [comment]
When I run it I get an internal MOSEK error that should usually not occur. I am looking into it.

**Comment by ulfworsoe** [comment]
I think you broke a record: A problem with one variable, one coefficient and no constraints found 3 distinct bugs in MOSEK.
I have passed the solution status bug to my colleague, and I'll get back as soon as it is solved.

**Comment by joehuchette** [comment]
Cool, thanks. Thought I was missing something obvious there for a while...

**Comment by ulfworsoe** [comment]
Apparently the presolve forgot about semidefinite variables concluded that
it was trivially feasible. A new build should be up sometime within a week.

On Fri, Jun 19, 2015 at 11:34 PM, Joey Huchette <notifications@github.com>
wrote:

> Cool, thanks. Thought I was missing something obvious there for a while...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Mosek.jl/issues/50#issuecomment-113650198>.
>



-- 
Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com
