### ISSUE TITLE
Conic duals fails Farkas test

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/Mosek.jl#56]
The attachment https://www.dropbox.com/sh/sjojrwff826zgn6/AABNrs_UFMlFSU1egPjzDVsDa?dl=0 contains a conic problem which I solve using Mosek. The julia program to solve the problem using Mosek is given here: https://gist.github.com/kaarthiksundar/10e645b8829a30a37d2e

The primal problem is infeasible and so I check the Farkas' certificate. Observe that the duals fail to satisfy the Farkas certificate. 

CC: @mlubin

**Comment by mlubin** [comment]
ECOS gives a valid certificate for ``TOL=1e-4``, but Mosek has a huge violation:
```
>> ||.|| = 8.434528581032842e8, rhs = 33.262782568756734
```

**Comment by kaarthiksundar** [comment]
There are cases where ECOS fails with that tolerance.

**Comment by ulfworsoe** [comment]
If I extract the underlying task and get the solution values directly, I get that
  ||A'y+slx-sux+snx|| ~ 1e-8
so it is probably a bug in the interface. I'll look at it.

**Comment by ulfworsoe** [comment]
Nope. That was a bug in MOSEK. I have passed it on to the interior-point guy.

**Comment by erling-d-andersen** [comment]
The problem is somewhat ill-posed. A lot of the conic constraints degenerate to one dimensional cones for instance which is a little bit strange but of course ok.

We are currently testing a fix that we plan to make public shortly.

**Comment by kaarthiksundar** [comment]
I ran the test instances with the fix (updated binaries) provided by mosek support. Preliminary tests indicate that the dual values pass the Farkas' test. I will check all the instances that failed the test previously and keep you guys posted by the end of the day. 

Thanks for the prompt response.

**Comment by kaarthiksundar** [comment]
The new binaries passed the Farkas' test for all the instances that I generated. Hence, closing the issue.
