### ISSUE TITLE
Mosek does not work with JuMP in Juliav0.4

### ISSUE THREAD

**Issue by 2nNguyen** [JuliaOpt/Mosek.jl#57]
Tried to run the qcp.jl example from JuMP using JuliaV0.4 and getting errors as below. The example works fine on JuliaV0.3.

Code:

using JuMP

m = Model()

@defVar(m, x)
@defVar(m, y >= 0)
@defVar(m, z >= 0)

@setObjective(m, Max, x)

@addConstraint(m, x + y + z == 1)
@addConstraint(m, x*x + y*y - z*z <= 0)
@addConstraint(m, x*x - y*z <= 0)

print(m)

status = solve(m)

Output:

Max x
Subject to
 x + y + z == 1
 x² + y² - z² <= 0
 x² - y*z <= 0
 x free
 y >= 0
 z >= 0

LoadError: UndefVarError: MosekSolver not defined
while loading In[4], in expression starting on line 23

 in model at C:\Users\Thuyen\.julia\v0.4\MathProgBase\src\defaultsolvers.jl:55
 in buildInternalModel at C:\Users\Thuyen\.julia\v0.4\JuMP\src\solvers.jl:236
 in solve at C:\Users\Thuyen\.julia\v0.4\JuMP\src\solvers.jl:77

**Comment by joehuchette** [comment]
to doing ``using Mosek`` at the top of your script.

**Comment by joehuchette** [comment]
Although perhaps I'm not understanding your question. Would you like to solve this with Mosek? Or are you confused as to why there is an error with ``MosekSolver`` in it when you do not have Mosek installed?

**Comment by 2nNguyen** [comment]
"to doing using Mosek at the top of your script."

I have tried that, and also m=Model(solver=MosekSolver()), same result.

**Comment by joehuchette** [comment]
Have you added the Mosek package with ``Pkg.add("Mosek")``? If so, you may need to build it with ``Pkg.build("Mosek")``.

**Comment by 2nNguyen** [comment]
>Although perhaps I'm not understanding your question. Would you like to solve this with Mosek? Or are you confused as to why there is an error with MosekSolver in it when you do not have Mosek installed?

I want to use the mosek solver but it appears it is not working. I have the solver installed.

>Have you added the Mosek package with Pkg.add("Mosek")? If so, you may need to build it with Pkg.build("Mosek")
 
I have added the mosek package. I removed it and added it again, and still the same error.
I installed JuliaV0.3 on another computer and added the package and it sucessfully solved the problem.

**Comment by mlubin** [comment]
@2nNguyen, could you restart julia and run ``using Mosek``? What happens?

**Comment by 2nNguyen** [comment]
>@2nNguyen, could you restart julia and run using Mosek? What happens?

to clarify, I have been using IJulia notebook to run the scripts.
"using Mosek" completes without output.

**Comment by mlubin** [comment]
Yes, please restart the julia kernel in IJulia and try running 
```
using Mosek
using JuMP

m = Model(solver=MosekSolver())

@defVar(m, x)
@defVar(m, y >= 0)
@defVar(m, z >= 0)

@setObjective(m, Max, x)

@addConstraint(m, x + y + z == 1)
@addConstraint(m, xx + yy - zz <= 0)
@addConstraint(m, xx - y*z <= 0)

status = solve(m)

```

**Comment by 2nNguyen** [comment]
>Yes, please restart the julia kernel in IJulia and try running 
> ...

LoadError: UndefVarError: xx not defined
while loading In[2], in expression starting on line 292

After editing xx->x*x, etc, the problem is solved sucessfully. Which was the step that solved my initial problem?

**Comment by joehuchette** [comment]
I'm guessing something left the Mosek package in a weird state, so just restarting the kernel fixed things.

**Comment by 2nNguyen** [comment]
Wow, this was a strange one, but I think the issue is resolved for me now, thank you Joe and mlubin.

Some info which might be relevant to others who encounter the same issue: I had been following one of the JuMP guides and added the cbc and ipopt packages  before adding the mosek package. Other than that it was a fresh install of Julia 0.4.0-pre+7133 and the IJulia package.
