### ISSUE TITLE
Error 1241: Too small maximum number of variables 0 is specified

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/Mosek.jl#58]
I get the following error when I do a conic program solve. What does this mean?

    MOSEK error 1241: Too small maximum number of variables 0 is specified. Currently, the number of variables is 2546.
    ERROR: MosekError(1241,"Too small maximum number of variables 0 is specified. Currently, the number of variables is 2546.")
     in putmaxnumvar at /nh/nest/u/harsha/.julia/v0.3/Mosek/src/msk_functions.jl:2980
     in loadconicproblem! at /nh/nest/u/harsha/.julia/v0.3/Mosek/src/MosekConicInterface.jl:235
     in loadconicproblem! at /nh/nest/u/harsha/.julia/v0.3/Mosek/src/MosekConicInterface.jl:208
     in lazyconstraintgenerator at /auto/nest/nest/u/harsha/Documents/Julia_codes/sccuc/UCcode/codejl/model.jl:433
     in lazycallback at /nh/nest/u/harsha/.julia/v0.3/JuMP/src/callbacks.jl:65
     in anonymous at /nh/nest/u/harsha/.julia/v0.3/JuMP/src/callbacks.jl:79
     in mastercallback at /nh/nest/u/harsha/.julia/v0.3/CPLEX/src/CplexSolverInterface.jl:416
    while loading /auto/nest/nest/u/harsha/Documents/Julia_codes/sccuc/UCcode/codejl/sccuc_simulation.jl, in expression starting on line 89

**Comment by mlubin** [comment]
Are you using a new mosek model, or are you calling ``loadconicproblem!`` repeatedly with the same model object?

**Comment by ulfworsoe** [comment]
This was a bug when resizing the underlying task in loadconic, basically when using loadconic to overwrite an existing problem. It should work in the head revision.

**Comment by mlubin** [comment]
@ulfworsoe, thanks for the fix! Did you push to master?

**Comment by ulfworsoe** [comment]
As far as I can see it has been in the master for some time. Unless this is
in fact a different bug.

On Thu, Oct 1, 2015 at 4:06 PM, Miles Lubin <notifications@github.com>
wrote:

> @ulfworsoe <https://github.com/ulfworsoe>, thanks for the fix! Did you
> push to master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Mosek.jl/issues/58#issuecomment-144737390>.
>



-- 
Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com

**Comment by mlubin** [comment]
Sorry, I misunderstood. Thought this was a recent fix.

**Comment by ulfworsoe** [comment]
This was fixed long ago.
