### ISSUE TITLE
lots of deprecation warnings

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Mosek.jl#59]
@ulfworsoe, Julia 0.4 release is around the corner. Mostly just requires replacing ``String`` with ``AbstractString`` and ``Uint8`` with ``UInt8``.

**Comment by ulfworsoe** [comment]
Should we drop 0.3 compatibility completely?

**Comment by mlubin** [comment]
In the other solver interfaces we've kept support for 0.3 and 0.4 for now, it's usually easier to do so than to branch. By that I mean, if you drop support for 0.3, you should release it as a new minor release, e.g., Mosek.jl 0.2.0, so that any bug fixes for 0.3 can still be released as Mosek.jl 0.1.5.
It's up to you though, we're not planning on continuing support for JuMP in 0.3 for long after the release of 0.4.

**Comment by mlubin** [comment]
Given that 0.4 is released today, it's safe to drop support for 0.3 unless you'd prefer not to.

**Comment by ulfworsoe** [comment]
I'll see if I can get it out of the way tomorrow, if not then monday.

On Fri, Oct 9, 2015 at 7:06 PM, Miles Lubin <notifications@github.com>
wrote:

> Given that 0.4 is released today, it's safe to drop support for 0.3 unless
> you'd prefer not to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Mosek.jl/issues/59#issuecomment-146933518>.
>



-- 
Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com
