### ISSUE TITLE
MOSEK 7.1 fails to install on Julia Version 0.4.0-dev+6002

### ISSUE THREAD

**Issue by steven-varga** [JuliaOpt/Mosek.jl#60]
Mosek fails to build on Julia 0.4.0-dev with the following error: 

The package declares 2 dependencies.
 - Library "libmosek"
    - Satisfied by:
      - Binaries at /home/steven/mosek/7/tools/platform/linux64x86/bin/libmosek64.so.7.1
    - Providers:
      - Binaries
 - Library "libmosekscopt"

INFO: Building Mosek

WARNING: deprecated syntax "[a=>b, ...]" at /home/steven/.julia/v0.4/Mosek/deps/build.jl:87.
Use "Dict(a=>b, ...)" instead.
============================================[ ERROR: Mosek ]============================================

LoadError: None of the selected providers can install dependency libmosek.
Use BinDeps.debug(package_name) to see available providers

while loading /home/steven/.julia/v0.4/Mosek/deps/build.jl, in expression starting on line 87

========================================================================================================

============================================[ BUILD ERRORS ]============================================

WARNING: Mosek had build errors.

 - packages with build errors remain installed in /home/steven/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Mosek")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================

Julia Version 0.4.0-dev+6002
Commit a802070 (2015-07-16 06:53 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.3

**Comment by mlubin** [comment]
First thing to try is updating to the 0.4.0 release. 0.4-dev versions are
not supported. ``Pkg.checkout("Mosek")`` (and then rebuild) may also help.

**Comment by steven-varga** [comment]
great idea! Pkg.checkout("Mosek"); fixed the problem. Thank you for your help.

**Comment by mlubin** [comment]
(@ulfworsoe, the package hasn't been tagged since the installation script was rewritten)

**Comment by ulfworsoe** [comment]
I have tagged a 0.2.0. It _should_ work on linux 32/64, windows 64 bit and
OS X (those are the platforms I do automatic tests on).

Is there anything I should do to make the release available to the package
manager?

On Sat, Oct 10, 2015 at 3:29 PM, Miles Lubin <notifications@github.com>
wrote:

> (@ulfworsoe <https://github.com/ulfworsoe>, the package hasn't been
> tagged since the installation script was rewritten)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Mosek.jl/issues/60#issuecomment-147089647>.
>



-- 
Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com

**Comment by mlubin** [comment]
If you use Pkg.tag() it will both create a git tag and set up a pull
request to METADATA.jl. Since the tag is already there, you could manually
create the PR or just remove the tag and run Pkg.tag("Mosek",v"0.2.0").

**Comment by ulfworsoe** [comment]
Ok, thank you. I'll do it first thing in the morning.

On Saturday, October 10, 2015, Miles Lubin <notifications@github.com> wrote:

> If you use Pkg.tag() it will both create a git tag and set up a pull
> request to METADATA.jl. Since the tag is already there, you could manually
> create the PR or just remove the tag and run Pkg.tag("Mosek",v"0.2.0").
> On Oct 10, 2015 11:10 AM, "Ulf Worsøe" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I have tagged a 0.2.0. It _should_ work on linux 32/64, windows 64 bit
> and
> > OS X (those are the platforms I do automatic tests on).
> >
> > Is there anything I should do to make the release available to the
> package
> > manager?
> >
> > On Sat, Oct 10, 2015 at 3:29 PM, Miles Lubin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > (@ulfworsoe <https://github.com/ulfworsoe>, the package hasn't been
> > > tagged since the installation script was rewritten)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/JuliaOpt/Mosek.jl/issues/60#issuecomment-147089647
> >.
> > >
> >
> >
> >
> > --
> > Ulf Worsøe
> > Mosek ApS
> >
> > ulf.worsoe@mosek.com
> <javascript:_e(%7B%7D,'cvml','ulf.worsoe@mosek.com');>
> > www.mosek.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/JuliaOpt/Mosek.jl/issues/60#issuecomment-147096609>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Mosek.jl/issues/60#issuecomment-147104246>.
>


-- 
Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com

**Comment by ulfworsoe** [comment]
Done (I think).

On Sun, Oct 11, 2015 at 7:20 PM, Ulf Worsoe <ulf.worsoe@mosek.com> wrote:

> Ok, thank you. I'll do it first thing in the morning.
>
>
> On Saturday, October 10, 2015, Miles Lubin <notifications@github.com>
> wrote:
>
>> If you use Pkg.tag() it will both create a git tag and set up a pull
>> request to METADATA.jl. Since the tag is already there, you could manually
>> create the PR or just remove the tag and run Pkg.tag("Mosek",v"0.2.0").
>> On Oct 10, 2015 11:10 AM, "Ulf Worsøe" <notifications@github.com> wrote:
>>
>> > I have tagged a 0.2.0. It _should_ work on linux 32/64, windows 64 bit
>> and
>> > OS X (those are the platforms I do automatic tests on).
>> >
>> > Is there anything I should do to make the release available to the
>> package
>> > manager?
>> >
>> > On Sat, Oct 10, 2015 at 3:29 PM, Miles Lubin <notifications@github.com>
>> > wrote:
>> >
>> > > (@ulfworsoe <https://github.com/ulfworsoe>, the package hasn't been
>> > > tagged since the installation script was rewritten)
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> https://github.com/JuliaOpt/Mosek.jl/issues/60#issuecomment-147089647>.
>> > >
>> >
>> >
>> >
>> > --
>> > Ulf Worsøe
>> > Mosek ApS
>> >
>> > ulf.worsoe@mosek.com
>> > www.mosek.com
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/JuliaOpt/Mosek.jl/issues/60#issuecomment-147096609
>> >.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/JuliaOpt/Mosek.jl/issues/60#issuecomment-147104246>.
>>
>
>
> --
> Ulf Worsøe
> Mosek ApS
>
> ulf.worsoe@mosek.com
> www.mosek.com
>
>
>


-- 
Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com
