### ISSUE TITLE
Downgraded Mosek Package

### ISSUE THREAD

**Issue by lroald** [JuliaOpt/Mosek.jl#66]
Hei,

When doing Pkg.update(), julia downgraded the Mosek package from v0.2 -> v0.1.12.
After downgrading, the below error occured when trying to build the downgraded package... 
I'm unsure about whether I should try to fix this, or try to/wait for an upgrade back to Mosek package v0.2 - any suggestions?

julia> Pkg.build("Mosek")
INFO: Building Mosek

WARNING: deprecated syntax "[a=>b, ...]" at C:\Users\lroald\.julia\v0.4\Mosek\de
ps\build.jl:81.
Use "Dict(a=>b, ...)" instead.
================================[ ERROR: Mosek ]================================

LoadError: None of the selected providers can install dependency libmosek.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\lroald\.julia\v0.4\Mosek\deps\build.jl, in expression sta
rting on line 81

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Mosek had build errors.

 - packages with build errors remain installed in C:\Users\lroald\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("Mosek")`
 - build a single package by running its `deps/build.jl` script

================================================================================

**Comment by mlubin** [comment]
Hi @lroald! Could you paste the output of ``Pkg.status()``? What version of Julia are you using?

**Comment by lroald** [comment]
I am using julia v0.4.1

julia> Pkg.status()
12 required packages:
 - CPLEX                         0.1.0
 - Clp                           0.2.0
 - DataFrames                    0.6.10
 - Debug                         0.1.6
 - ForwardDiff                   0.1.2
 - Gadfly                        0.4.0
 - Gurobi                        0.2.0
 - JuMP                          0.11.1
 - JuMPChance                    0.2.2
 - MAT                           0.2.14
 - MatpowerCases                 0.3.2
 - Mosek                         0.1.2
46 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.19
 - Blosc                         0.1.4
 - Calculus                      0.1.14
 - Cbc                           0.2.0
 - Codecs                        0.1.5
 - ColorTypes                    0.2.0
 - Colors                        0.6.0
 - Compat                        0.7.8
 - Compose                       0.4.0
 - Contour                       0.0.8
 - DataArrays                    0.2.20
 - DataStructures                0.3.13
 - Dates                         0.4.4
 - Distances                     0.2.1
 - Distributions                 0.8.7
 - Docile                        0.5.19
 - DualNumbers                   0.1.5
 - ECOS                          0.6.0
 - FixedPointNumbers             0.1.1
 - GZip                          0.2.18
 - Grid                          0.4.0
 - HDF5                          0.5.7
 - Hexagons                      0.0.4
 - ImmutableArrays               0.0.11
 - Iterators                     0.1.9
 - JSON                          0.5.0
 - KernelDensity                 0.1.2
 - LibExpat                      0.1.0
 - Loess                         0.0.5
 - MathProgBase                  0.4.0
 - Measures                      0.0.1
 - NaNMath                       0.1.1
 - Optim                         0.4.4
 - PDMats                        0.3.6
 - Reexport                      0.0.3
 - ReverseDiffSparse             0.2.11
 - SHA                           0.1.2
 - Showoff                       0.0.6
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.7.4
 - StatsFuns                     0.2.0
 - URIParser                     0.1.1
 - WinRPM                        0.1.13
 - WoodburyMatrices              0.1.2
 - Zlib                          0.1.12

**Comment by lroald** [comment]
on windows, 64 bit

**Comment by mlubin** [comment]
@lroald, try running ``Pkg.update()`` now

**Comment by lroald** [comment]
@mlubin, thanks a lot! Issue disappeared.
