### ISSUE TITLE
Ctrl-c when optimizing in MOSEK

### ISSUE THREAD

**Issue by ulfworsoe** [JuliaOpt/Mosek.jl#69]
Pressing Ctrl-c during a call to a native MOSEK function appears to immediately return, leaving the underlying Task in a inconsistent state. When the Mosek.Task object is subsequently destroyed, deleting the underlying object may result in a crashes.

Original post: https://groups.google.com/forum/#!topic/julia-opt/NHKXe4L2b0g

**Comment by mlubin** [comment]
See the fix for this in CPLEX.jl: https://github.com/JuliaOpt/CPLEX.jl/pull/46

I can't say that I understand it all myself, but it should be possible to get something working with a bit of fiddling.

Also related: https://github.com/JuliaOpt/Gurobi.jl/pull/53

**Comment by ulfworsoe** [comment]
Looking at this again. I am not sure the approach from Gorobi or CPLEX will apply to MOSEK. I am not entirely sure what CPLEX does (they appear to save SIGINT, but I can't see what they use it for), but Gurobi appears to forcably delete the model if the user breaks during optimization.
Ideally, what I want is something like this: 
```
break_flag = false
function msk_siginthandler(v)
  global break_flag = true
end

function optimize()
  old_siginthandler = signal(SIGINT,msk_siginthandler)
  ccall(:MSK_optimize,...)
  signal(SIGINT,old_siginthandler)
end
```
The callback function from the task can check  and reset ``break_flag``. This way we can break cleanly and even return any solution information that might be available.

It appears to work on linux and osx (as in: It hasn't crashed yet), but I suspect it is probably not a robust solution since it involved invoking Julia code (however simple) in a signal handler. But: _not_ doing this almost guarantees a crash.

It can probably be made robust by putting the signal handler and the ``break_flag`` in C code.

**Comment by mlubin** [comment]
What's unsafe about running Julia code in a signal handler?

**Comment by ulfworsoe** [comment]
I don't know exactly. According to Karpinski this solution is "very unlikely to be reliable" (https://groups.google.com/forum/#!topic/julia-users/AJVSX_0HghQ). If you are absolutely positive that the signal handler will execute in Julia's main thread, it will probably work. However, if you get a signal during something multithreaded (like MOSEK optimize or a an MKL function) it is not necessary well-defined which thread the signal handler executes in, and in theory it can lead to executing Julia code in two thread in parallel.

I don't know the internals of Julia, but I would guess that it is highly unlikely, but not impossible, that this solution might crash. I could just throw it out in the wild and see what happens...

**Comment by mlubin** [comment]
That response is a bit outdated, before there was any threading work in Julia. It's worth asking the question again on the julia-users list.

**Comment by ulfworsoe** [comment]
I gather that the signal handling solution willl not work in Julia 0.5. I have come up with an alternative solution that appears to work as far as I have tested it (implented in branch sigint2):
```
function optimize(task_:: MSKtask)
  trmcode_ = Array(Int32,(1,))

  res =
    disable_sigint() do
        @msk_ccall( "optimizetrm",Int32,(Ptr{Void},Ptr{Int32},),task_.task,trmcode_)
    end

  if res != MSK_RES_OK
    msg = getlasterror(task_)
    throw(MosekError(res,msg))
  end
  (convert(Int32,trmcode_[1]))
end
```
and the tricky part, checking for ctrl-c in the callback function:
```
function msk_info_callback_wrapper(t::Ptr{Void}, userdata::Ptr{Void}, where :: Int32, douinf :: Ptr{Float64}, intinf :: Ptr{Int32}, lintinf :: Ptr{Int64})
    r = if unsafe_load(cglobal(:jl_signal_pending, Cint),1) > Cint(0) # Not so good... jl_signal_pending is actually a sig_atomic_t...
            1
        else
            task = unsafe_pointer_to_objref(userdata) :: MSKtask
            if task.usercallbackfunc == nothing
                0
            else
                dinfa  = pointer_to_array(douinf,(MSK_DINF_END,),false)
                iinfa  = pointer_to_array(intinf,(MSK_IINF_END,),false)
                liinfa = pointer_to_array(lintinf,(MSK_LIINF_END,),false)

                task.usercallbackfunc(Int32(where), dinfa, iinfa, liinfa)
            end
        end
    
    convert(Cint,r)::Cint
end
```

**Comment by ulfworsoe** [comment]
Fixed. Found a way to check for c-break.
