### ISSUE TITLE
bug in freemodel!

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Mosek.jl#70]
This line [here](https://github.com/JuliaOpt/Mosek.jl/blob/6d4daa8514bbeb6eeb96fc340200c1904ec8d32e/src/MosekLPQCQPInterface.jl#L665) is assigning ``C_NULL`` to a ``Mosek.MSKtask`` object. Is it safe to delete this line?

**Comment by mlubin** [comment]
CC @emreyamangil @chriscoey

**Comment by erling-d-andersen** [comment]
To me it looks safe. Just do not use the task after it has been deleted.
Den 21. mar. 2016 8.55 PM skrev "Miles Lubin" <notifications@github.com>:
>
> This line here is assigning C_NULL to a Mosek.MSKtask object. Is it safe
to delete this line?
