### ISSUE TITLE
MOSEK warning

### ISSUE THREAD

**Issue by dvij** [JuliaOpt/Mosek.jl#74]
I'm solving several instances of a problem in a loop and keep getting the following warning:
MOSEK warning 705: 1 near zero elements are specified in sparse row ''(19) of matrix 'A'.
This is not a problem in my model and does not affect solution quality, but is creates clutter when the warning is repeatedly printed on my terminal. Is there a simple way to suppress this?

**Comment by ulfworsoe** [comment]
There is no facility to disable individual warnings, but you can set the integer parameter "MAX_NUM_WARNINGS" to 0. This should effectively disable warnings.
