### ISSUE TITLE
Slow to Download Mosek distro

### ISSUE THREAD

**Issue by memoiry** [JuliaOpt/Mosek.jl#75]
Hi

I have installed mosek distribution and put it in /users/myname with the license. I have tried `
`Pkg.clone("https://github.com/JuliaOpt/Mosek.jl")`
Pkg.build("Mosek")
`
while Pkg.add("Mosek") seems make no sense.

but the build process was stuck 

julia> Pkg.build("Mosek")
INFO: Building Mosek
INFO: Download MOSEK distro (http://download.mosek.com/stable/7/mosektoolsosx64x86.tar.bz2)

it just keeps showing this, maybe something goes wrong with my internet connection. But I have actually downloaded it by myself,  can I just skip this process and build it manually ?

thx for help

**Comment by ulfworsoe** [comment]
The installer should look for MOSEK in the default installation path (your home directory). You can download an unpack it there. Alternatively, you can set the environment variable MOSEK_7_1_BINDIR to point to the bin directory in the mosek distro where you have unpacked it (e.g. MOSEK_7_1_BINDIR=mosek/7/tools/platform/linux64x86/bin). Once the package is installed, you don't need the environment variable.

I cannot explain why the download should stall. The distro packages are hosted on Amazon, I we have never experienced problems before. Which platform are you on (osx/windows/linux)?

**Comment by memoiry** [comment]
@ulfworsoe hi, I'm using osx. I have indeed put the mosek into my home directory, but it still keeps downloading from the internet, which seems cause some problems...

**Comment by ulfworsoe** [comment]
It appears to ignore the path. I'm looking into it.

**Comment by ulfworsoe** [comment]
The builder script should now pick up a MOSEK installed in your home, but you will have to get the HEAD revision of Mosek. Basically do:
```
Pkg.checkout("Mosek","master")
Pkg.build("Mosek")
```
