### ISSUE TITLE
error "Invalid SDP cone definition"

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Mosek.jl#76]
I'm running the [mathprogbase conic SDP tests](https://github.com/JuliaOpt/MathProgBase.jl/blob/master/test/conicinterface.jl#L456) (which aren't currently run by default, tho I submitted a pull request for that), and I'm getting this error:
```
ERROR: LoadError: Mosek.MosekMathProgSolverInterface.MosekMathProgModelError("Invalid SDP cone definition")
 in countcones at /Users/chris/.julia/v0.4/Mosek/src/MosekConicInterface.jl:629
 in loadproblem! at /Users/chris/.julia/v0.4/Mosek/src/MosekConicInterface.jl:116
 in loadproblem! at /Users/chris/.julia/v0.4/Mosek/src/MosekConicInterface.jl:93
 in loadproblem! at /Users/chris/.julia/v0.4/Mosek/src/MosekConicInterface.jl:82
 in conicSDPtest at /Users/chris/.julia/v0.4/MathProgBase/test/conicinterface.jl:508
```
I think the two problems are well posed in conic format (following [this pull request](https://github.com/JuliaOpt/MathProgBase.jl/pull/106) at least).

I looked at the code for `countcones` and I may be daft but I don't get it...
```
for (sym,idxs) in cones
        if ! (sym in msk_accepted_cones)
            throw(MosekMathProgModelError("Unsupported cone type"))
        end
        vecsize += length(idxs)
        
        if     sym == :SDP
            n = round(Int32,sqrt(.25+2*length(idxs))-0.5)
            if n*(n+1)/2 != size(idxs,1) # does not define the lower triangular part of a square matrix
                throw(MosekMathProgModelError("Invalid SDP cone definition"))
            end
```
Because `length(idxs) = size(idxs,1)`.

**Comment by mlubin** [comment]
The SDP tests were never updated to the new format a long time ago, so they're not expected to pass

**Comment by chriscoey** [comment]
going to update the SDP tests
