### ISSUE TITLE
error when adding mosek package 

### ISSUE THREAD

**Issue by zhenzhenyan** [JuliaOpt/Mosek.jl#88]
Hi

I was trying to build mosek using Pkg.build("Mosek") and then encounter such an error

At line:1 char:3
+ --help
+   ~
Missing expression after unary operator '--'.
At line:1 char:3
+ --help
+   ~~~~
Unexpected token 'help' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

ERROR: LoadError: No download agent available; install curl, wget, or fetch.
 in download_cmd at C:\Users\a0109727\AppData\Local\Julia-0.4.6\v0.4\Mosek\deps\liftedfrombindeps.jl:39
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in debug_context at C:\Users\a0109727\AppData\Local\Julia-0.4.6\v0.4\BinDeps\src\debug.jl:54
 in debug at C:\Users\a0109727\AppData\Local\Julia-0.4.6\v0.4\BinDeps\src\debug.jl:59
 in debug at C:\Users\a0109727\AppData\Local\Julia-0.4.6\v0.4\BinDeps\src\debug.jl:65
while loading C:\Users\a0109727\AppData\Local\Julia-0.4.6\v0.4\Mosek\deps\build.jl, in expression starting on line 76

Can anybody help me?

My versioninfo(true) is as follows:

Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
           Microsoft Windows [Version 10.0.10586]
Memory: 7.922718048095703 GB (4421.21875 MB free)
Uptime: 5908.1167739 sec
Load Avg:  0.0  0.0  0.0
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz:
       speed         user       nice        sys       idle        irq ticks
#1  3408 MHz     216687          0     335250    5355328      53812 ticks
#2  3408 MHz      60343          0     133843    5712921       1671 ticks
#3  3408 MHz      98656          0     216750    5591703        828 ticks
#4  3408 MHz     131953          0     144984    5630171       1203 ticks
#5  3408 MHz     125781          0     243312    5538015       1171 ticks
#6  3408 MHz      57218          0     143156    5706734        906 ticks
#7  3408 MHz     126859          0     206093    5574156        578 ticks
#8  3408 MHz      75000          0     144312    5687796       1250 ticks

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  CCHZPATH = C:\CTEX\CTeX\cct\fonts
  CCPKPATH = C:\CTEX\CTeX\fonts\pk\modeless\cct\dpi$d
  GUROBI_HOME = C:\gurobi652\win64
  HOMEDRIVE = H:
  HOMEPATH = \
  HOMESHARE = \\fs5\stuhome\a01\a0109727
  JULIA_PKGDIR = C:\\Users\\a0109727\\AppData\\Local\\Julia-0.4.6
  PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

Package Directory: C:\Users\a0109727\AppData\Local\Julia-0.4.6\v0.4
9 required packages:
 - BinDeps                       0.4.2
 - Convex                        0.3.0
 - Gurobi                        0.2.3
 - JuMP                          0.14.0
 - LibCURL                       0.2.0
 - MAT                           0.2.14
 - Mosek                         0.4.0+             master
 - SCS                           0.2.5
 - WinRPM                        0.2.0
16 additional packages:
 - Blosc                         0.1.6
 - Calculus                      0.1.15
 - Compat                        0.8.7
 - DataStructures                0.4.5
 - ForwardDiff                   0.2.2
 - HDF5                          0.6.5
 - Lazy                          0.11.0
 - LegacyStrings                 0.1.1
 - LibExpat                      0.2.0
 - MacroTools                    0.3.2
 - MathProgBase                  0.5.3
 - NaNMath                       0.2.1
 - ReverseDiffSparse             0.5.8
 - SHA                           0.2.1
 - URIParser                     0.1.6
 - Zlib                          0.1.12

thanks for your help

**Comment by ulfworsoe** [comment]
On windows it should actually use a powershell command to download the package (or wget, curl or fetch if they are available). Make sure that powershell is installed and available from the prompt.

**Comment by zhenzhenyan** [comment]
Hi,
I did use the powershell command to add mosek package. And it is ok to install gurobi etc except mosek.

**Comment by ulfworsoe** [comment]
Ah, yes. Got it. Detection of powershell always failed. If you pull the head revision it should work. Please reopen this bug is the problem persists.
