### ISSUE TITLE
getsolvetime returns zero when solving MIO

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Mosek.jl#91]
Is ``MSK_DINF_OPTIMIZER_TIME`` the right property to access when solving a problem with integer variables or should it be ``MSK_DINF_MIO_TIME``?

**Comment by erling-d-andersen** [comment]
MSK_DINF_OPTIMIZER_TIME works for all optimizers and is the total time.

2016-08-19 22:03 GMT+02:00 Miles Lubin <notifications@github.com>:

**Comment by mlubin** [comment]
Something seems to be broken. I'm using Mosek 8 and both ``Mosek.getdouinf(m.task,Mosek.MSK_DINF_OPTIMIZER_TIME)`` and ``Mosek.getdouinf(m.task,Mosek.MSK_DINF_MIO_TIME)`` return zero after any solve.

**Comment by erling-d-andersen** [comment]
That is strange we will investigate it.

2016-08-23 21:56 GMT+02:00 Miles Lubin <notifications@github.com>:

**Comment by ulfworsoe** [comment]
I cannot reproduce this (fresh checkout and latest MOSEK 8 build). Do you have an example of a problem that does this?

**Comment by mlubin** [comment]
Here's an example: https://gist.github.com/mlubin/87dcda2792b79295ca573cc0867744f7

My version is:
```
julia> Mosek.getversion()
(8,0,0,34)
```

**Comment by ulfworsoe** [comment]
Some of the MSK_DINF_... constants had changed values. I have updated the interface accordingly.

**Comment by mlubin** [comment]
Thanks, @ulfworsoe. Worth adding a test for this?

**Comment by ulfworsoe** [comment]
Yes, it might be... I'll see what I can figure out. 

In principle this should never happen (and it only happened now because mosek 8 is still in beta and things are still being shuffled around). But we should have a test for when it happens anyway.

**Comment by ulfworsoe** [comment]
I have pushed tests for all constant values for MOSEK 7.1 and 8.0.
