### ISSUE TITLE
Infeasible incorrectly reported as unbounded

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Mosek.jl#94]
Mosek is failing JuMP's unit test:

```jl
using JuMP, Mosek

m2 = Model(solver=MosekSolver())

@variable(m2, x2 >= 0)
@constraint(m2, x2 <= 1)
@objective(m2, Max, x2)
@constraint(m2, c2, norm(x2) <= x2 - 1)

status = solve(m2)
```

The problem is infeasible but Mosek 8.0.0.34 reports unbounded. The test used to pass with Mosek 7.

**Comment by joachimdahl** [comment]
@mlubin Is there an easy way to generate MOSEK .task files from JuMP?  That makes MOSEK support much easier, as we can then reproduce the solver problem directly using the MOSEK CLI.

**Comment by mlubin** [comment]
@joachimdahl, yes:

```jl
using JuMP, Mosek

m2 = Model(solver=MosekSolver())

@variable(m2, x2 >= 0)
@constraint(m2, x2 <= 1)
@objective(m2, Max, x2)
@constraint(m2, c2, norm(x2) <= x2 - 1)

JuMP.build(m2)
Mosek.writedata(internalmodel(m2).task,"problem.task")
```

**Comment by erling-d-andersen** [comment]
There is a bug that will be fixed in the next version 8. It should be
available today or within the next few days. Keep an eye on website or
twitter.

2016-08-26 17:27 GMT+02:00 Miles Lubin <notifications@github.com>:

**Comment by erling-d-andersen** [comment]
New version 8 is now available from our website.

2016-08-29 10:21 GMT+02:00 Erling Andersen <erling@andersens.name>:

**Comment by blegat** [comment]
I just tested on 8.0.0.37(Beta) and the solver reports `Infeasible`
