### ISSUE TITLE
updating RHS on a conic model

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Mosek.jl#96]
@chriscoey and I are solving a sequence of small-ish conic models in a loop where the only changing data is the `b` vector in the [MPB conic form](http://mathprogbasejl.readthedocs.io/en/latest/conic.html). I've noticed that the time taken by `loadproblem!` is on the same order of magnitude as the amount of time taken by `optimize!`.

This leads to two questions:
1) Does Mosek in principle support updating the data in a conic (SOCP/SDP) model like this?
2) If so, what's a reasonable way to expose this functionality at the level of the MPB abstraction?

**Comment by erling-d-andersen** [comment]
Surprising but the optimizers are really efficient.

1) In the low level C API you can modify anything for SOCP/SDP models.
Changing for instance one element in the RHS should have O(1) complexity.
2) I am not familliar with MPB.





2016-09-15 16:14 GMT+02:00 Miles Lubin <notifications@github.com>:

**Comment by mlubin** [comment]
>  In the low level C API you can modify anything for SOCP/SDP models.
Changing for instance one element in the RHS should have O(1) complexity.

That's good then. Maybe @ulfworsoe can comment on the second point.

**Comment by erling-d-andersen** [comment]
Can do this fast with optimizer say GuRoBi or Cplex for an LP?

2016-09-15 18:22 GMT+02:00 Miles Lubin <notifications@github.com>:

**Comment by mlubin** [comment]
Yes, the LP interface has methods for this:
[setconstrLB!](http://mathprogbasejl.readthedocs.io/en/latest/lpqcqp.html#setconstrLB!)
[setconstrUB!](http://mathprogbasejl.readthedocs.io/en/latest/lpqcqp.html#setconstrUB!)

**Comment by erling-d-andersen** [comment]
I would guess they work SOCP and SDP too. Did you try it.

2016-09-16 10:56 GMT+02:00 Miles Lubin <notifications@github.com>:

**Comment by erling-d-andersen** [comment]
We do not have special APIs LPs, SOCPs, and SDPs. So if something work for
LP it works SOCP too.

2016-09-16 11:24 GMT+02:00 Erling Andersen <erling@andersens.name>:

**Comment by mlubin** [comment]
@erling-d-andersen, there is a nontrivial [mapping](https://github.com/JuliaOpt/Mosek.jl/blob/fcce22463b36f017374d849fdd6a42039cfca287/src/MosekConicInterface.jl#L14) from the MPB conic form to the C API, plus rescaling of the SDP cone, so it cannot just work as is.

**Comment by erling-d-andersen** [comment]
Ok. The low level MOSEK C API works as I described.

2016-09-16 11:28 GMT+02:00 Miles Lubin <notifications@github.com>:

**Comment by ulfworsoe** [comment]
To partially repeat @erling-d-andersen:
1. Coefficients for linear and conic quadratic variables (in ``A``) can be modified, and ``b`` can be modified. Coefficient matrixes for semidefinite variables cannot me modified, but an entire coefficient matrix can be replaced.
2. Modifications right-hand sides and to non-PSD coefficients should be reasonably easy to implement. Changes to PSD coefficients is a bit more complicated but still possible.

I can also take a look at the ``loadproblem!`` if there is anything that takes an unreasonable amount of time.

**Comment by mlubin** [comment]
We now have an interface in MPB to update the ``b`` vector: https://github.com/JuliaOpt/MathProgBase.jl/pull/124.
Now just need an implementation of it here!

**Comment by chriscoey** [comment]
Hey @ulfworsoe, it would be great for us to have this implemented when we run our tests for Pajarito+Mosek in our upcoming paper

**Comment by ulfworsoe** [comment]
They have been enabled in master now. I had forgotten to prefix the functions with `MathProgBase.` namespace.

**Comment by chriscoey** [comment]
@mlubin @ulfworsoe This issue can be closed I think
