### ISSUE TITLE
Mosek beta 8.0.0.37 regression compared to Mosek beta 8.0.0.34

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/Mosek.jl#98]
Now that I upgraded to Mosek 8.0.0.37, one program I had that worked with Mosek 8.0.0.34 and returned `:Infeasible` now returns `:Stall`.
This program is [this MAXCUT instance](https://github.com/blegat/SumOfSquares.jl/blob/9c4cc3184afe3e359ec8d14fb47726b50edb22ae/test/sosdemo6.jl).

**Comment by joehuchette** [comment]
cc @ulfworsoe

**Comment by ulfworsoe** [comment]
Thank you. I will see what I can do.

**Comment by ulfworsoe** [comment]
It is clearly a regression between in the MOSEK solver. I will close the bug when we have a build that fixes it.

**Comment by erling-d-andersen** [comment]
That can happen. Whether this is a bug or just bad luck is hard to say
without seeing the problem.

Den 21. okt. 2016 3.40 PM skrev "Benoît Legat" <notifications@github.com>:

**Comment by joachimdahl** [comment]
We don't have satisfactory solution for at the moment.   The current implementation works best for the  majority of our problems, but regrettably stalls for this instance.

**Comment by joachimdahl** [comment]
A new version MOSEK 8.0.0.41 is available from the MOSEK website.  This version seems to correctly determine infeasibility for the reported test problem.

**Comment by blegat** [comment]
@joachimdahl Indeed, it works great now, thanks a lot !
