### ISSUE TITLE
ILL_POSED problem causes "Internal value error"?

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Mosek.jl#99]
Hi @ulfworsoe,

I solved a small SDP problem with MOSEK through Mosek.jl, and after MOSEK was done with iterations, Julia had a `ERROR: LoadError: Internal value error`. I dumped the MOSEK task and ran it from command line. The solution file started with:
```
NAME                : 
PROBLEM STATUS      : ILL_POSED
SOLUTION STATUS     : PRIMAL_ILLPOSED_CER
OBJECTIVE NAME      : OBJ
PRIMAL OBJECTIVE    : 4.58097580e-05    
DUAL OBJECTIVE      : 5.31698634e-05    
```

I have run into this `ERROR: LoadError: Internal value error` on SOC problems with MOSEK too. Is Mosek.jl not handling the `ILL_POSED` MOSEK status properly? Are there other statuses that Mosek.jl may not be handling either? A fix for this would be extremely helpful for our testing of Pajarito, because it could tell us whether these Mosek.jl errors we are encountering are all just due to strong duality failures (or whatever else could cause `ILL_POSED` - ideally the MOSEK statuses returned would be more informative).

@mlubin

**Comment by ulfworsoe** [comment]
`ILL_POSED` should be handled correctly. `LoadError: Internal value error` sounds like a NULL-pointer error being handled by Julia. 

 Do you have a Julia example that reproduces it?

**Comment by chriscoey** [comment]
Here is an example:

```
using MathProgBase
using Mosek
m = MathProgBase.ConicModel(MosekSolver())
MathProgBase.loadproblem!(m,
       [ 0.0, 0.0, 1.0],
       [ -1.0  0.0  0.0;
        -1.0  0.0  0.0;
         0.0 -1.0  0.0;
         0.0  0.0 -1.0],
       [ 0.0, 0.0, 0.0, 0.0],
       Any[(:Zero,1:1),(:SOCRotated,2:4)],
       Any[(:Free,[1,2,3])])
MathProgBase.optimize!(m)
MathProgBase.status(m)
MathProgBase.getobjval(m)
MathProgBase.getsolution(m)
```

The following occurs:
```
julia> MathProgBase.status(m)
ERROR: Internal value error
 in status(::Mosek.MSKtask, ::Int32) at /Users/coey/.julia/v0.5/Mosek/src/MosekSolverInterface.jl:71
 in status(::Mosek.MosekMathProgSolverInterface.MosekMathProgConicModel) at /Users/coey/.julia/v0.5/Mosek/src/MosekConicInterface.jl:597
```

I sent Erling this problem, he responded with the following:

> MOSEK never says unbounded. It will say dual infeasible or dual illposed perhaps. Could be the Julia interface is messing things up or you interprete the MOSEK output incorrectly.
> 
> On my computer MOSEK says
> 
> Interior-point solution summary
> Problem status : ILL_POSED
> Solution status : DUAL_ILLPOSED_CER
> Primal. obj: -8.2055136956e-008 nrm: 4e+000 Viol. con: 0e+000 var: 0e+000 cones: 9e-016
> 
> which is correct. Your problem is illposed. Right?
> 
> If you make tiny perturbation e.g. say
> 
> x = 1.0e-16
> 
> then your problem is unbounded. Right? That is by definition illposed.

So it seems to me that Mosek.jl fails to correctly handle MOSEK statuses.

**Comment by ulfworsoe** [comment]
Thank you. It was as you said, the Mosek MathProgBase interface that did not handle certificates correctly.
